### ISSUE TITLE
Max readable comments in card

### ISSUE THREAD

**Issue by agustinscaz** [gregsdennis/Manatee.Trello#100]
Hi,

How is the correct way to read all the comments in a card? when I try to read, I only get the last 50 comments.

Is there a way to read all the comments?

Thanks in advance!

**Comment by gregsdennis** [comment]
There is a `.Limit(int)` extension method on collections. This will alter the request to specify a different number of returned items. There is a Trello-imposed limit of 1000.

**Comment by agustinscaz** [comment]
Perfect, thanks a lot!
