### ISSUE TITLE
RestSharp - Method 'get_StatusCode' does not have an implementation

### ISSUE THREAD

**Issue by mathieuchateau** [gregsdennis/Manatee.Trello#102]
Hello,

I am trying to implement Manatee.Trello in my program. I am currently stuck with Framework 4 as I wish to still works on Windows XP (backward...)

Env:
-Visual Studio Pro 2015
-Latest version of nuggets.

Error:

> Method 'get_StatusCode' in type 'Manatee.Trello.RestSharp.RestSharpResponse' from assembly 'Manatee.Trello.RestSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=783b036be1eaf5a7' does not have an implementation.

Code generating exception: 
`var addToList = new List("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz");`

Stack:
   

> at Manatee.Trello.Internal.ExceptionHandling.DebugLog.Error(Exception e, Boolean shouldThrow) in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\Internal\ExceptionHandling\DebugLog.cs:line 26
>    at Manatee.Trello.Internal.DataAccess.JsonRepository.ValidateResponse(IRestRequest request) in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\Internal\DataAccess\JsonRepository.cs:line 64
>    at Manatee.Trello.Internal.DataAccess.JsonRepository.Execute[T](TrelloAuthorization auth, Endpoint endpoint, IDictionary`2 parameters) in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\Internal\DataAccess\JsonRepository.cs:line 29
>    at Manatee.Trello.Internal.Synchronization.SynchronizationContext`1.Merge() in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\Internal\Synchronization\SynchronizationContext.cs:line 160
>    at Manatee.Trello.Internal.Synchronization.SynchronizationContext.Synchronize(Boolean force) in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\Internal\Synchronization\SynchronizationContext.cs:line 63
>    at Manatee.Trello.List.get_Id() in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\List.cs:line 82
>    at Manatee.Trello.ReadOnlyCardCollection..ctor(Type type, Func`1 getOwnerId, TrelloAuthorization auth) in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\CardCollection.cs:line 38
>    at Manatee.Trello.List..ctor(String id, TrelloAuthorization auth) in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\List.cs:line 177
>    at XXX.XXXClasses.Trello.Initialize() in F:\XXXXX\Trello.cs:line 25

**Comment by gregsdennis** [comment]
So this is happening in .net 4 as well? Okay. 

Could you copy your comment over to #32, please? That's where I'm tracking this issue.

I thought it was limited to .net 4.5+, but I suppose I need to re-evaluate.

**Comment by gregsdennis** [comment]
I have confirmed that the property is missing, and it's the same problem as the issue referenced above, just with RestSharp instead of WebApi.  I'll have an update published soon.

**Comment by gregsdennis** [comment]
@mathieuchateau, please see Manatee.Trello.RestSharp v1.3.1 now available on Nuget.
