### ISSUE TITLE
Cannot use Linq operations on collections

### ISSUE THREAD

**Issue by insomniac235** [gregsdennis/Manatee.Trello#105]
Hello. I'm aware that this might not be an issue per se, but I don't know where else to put it, since this repository is pretty active and someone else also might stumble upon this issue if they encounter it while using the library.

The thing I'm trying to accomplish is to access Lists and Boards and Cards without an Id, that is without using the constructor that accepts the id as a parameter. To do that I tried using Linq Where method to check for equality based on name. Whenever I try to do that I receive a ```sequence contains no elements``` exception. 

Using the search feature seems to be an overkill for this kind of thing and I can't find anything else.

Here is an example of code that raises such an exception:
```csharp
CustomCard customCard = customBoard.Lists.Where(l => l.Equals(listName)).First().Cards.Where(c => c.Call.Equals(cardCall)).First();
```

**Comment by gregsdennis** [comment]
Thanks for reporting the concern.

All of the collections in Manatee.Trello derive from standard .Net collection types and are therefore fully Linq-compatible.

Regarding your code snippet,

1. What is a `CustomCard`?
1. What is `.Call`?  That is not a property on the `Card` entity.
1. It appears you're comparing `l` (a `List`) with `listName` which I expect is a string.  The `.Equals()` method will never return `true` for this (probably the source of your exception).  You'll need to compare `l.Name` with `listName`.
1. You can eliminate the `.Where()` and just use `.First()` call with the lambda expression, though I would suggest using `.FirstOrDefault()`.  This will ensure that you don't get an exception if there isn't a match.

Also, I would also split up the query to better isolate where it's failing.  Something like this:

    var list = customBoard.Lists.FirstOrDefault(l => l.Name == listName);
    var card = list.Cards.FirstOrDefault(c => ...);  // I'm not sure what you're comparing here.

If you're trying to find entities without IDs then I think you're on the right track.  I also suggest you start with the `Member.Me` static property.  From there you can get your boards and organizations.

**Comment by gregsdennis** [comment]
@insomniac235 ping!
