### ISSUE TITLE
Manatee.Trello.CustomFields - Unable to resolve dependencies. 'Manatee.Json 8.1.0' is not compatible with 'Manatee.Trello.CustomFields 1.1.0 constraint

### ISSUE THREAD

**Issue by mathieuchateau** [gregsdennis/Manatee.Trello#107]
Following last update:

Unable to resolve dependencies. 'Manatee.Json 8.1.0' is not compatible with 'Manatee.Trello.CustomFields 1.1.0 constraint: Manatee.Json (>= 6.0.0 && < 7.0.0)', 'Manatee.Trello.ManateeJson 1.8.1 constraint: Manatee.Json (>= 6.0.0 && < 7.0.0)'.

**Comment by gregsdennis** [comment]
This isn't an issue.

Manatee.Json 7+ is .Net Standard. As such it is only supported by .Net Framework 4.6.1+.

**Comment by mathieuchateau** [comment]
No problem for closing but I don't get it.

I have  nugget installed. When trying to update them, now it says CustomField cannot be updated due to constraint. So I have to drop it to get newer version.

From my understanding, CustomField nugget should be updated to accept newer version of ManateeJson ?

**Comment by gregsdennis** [comment]
Manatee.Trello.ManateeJson and Manatee.Trello.CustomFields both depend on Manatee.Json versions >=6.0.0 & < 7.0.0.  You'll have to ensure you have a version that is compatible.

The latest compatible version is 6.0.3.  This should automatically download with both of the Trello libraries.

As mentioned, the update to the newer package will come along with the upgrade to .Net Standard.
