### ISSUE TITLE
LabelSearchParameter

### ISSUE THREAD

**Issue by LeXX** [gregsdennis/Manatee.Trello#108]
Hello!

```
var query = SearchFor.Label(LabelColor.Green | LabelColor.Red);
var cards = new Search(query, null, SearchModelType.Cards, new[] { board }).Cards.ToList();
```
not working, got 'invalid token' error from Manatee.Trello

```
var cards = new Search(SearchFor.Label(LabelColor.Green), null, SearchModelType.Cards, new[] { board }).Cards.ToList();
```
not working, got 'invalid token' error from Manatee.Trello

```
var cards = new Search("label:red", null, SearchModelType.Cards, new[] { board }).Cards.ToList();
```
work! SearchFor.Text("label:blue") work too

`new Search(SearchFor.Text("#green"), null, SearchModelType.Cards, new[] { board }).Cards.ToList();`
not working, got 'invalid token' error from Manatee.Trello

Also
`SearchFor.Label(LabelColor.Green | LabelColor.Red)`
return "#purple" - its fine?

`SearchFor.Text("label:yellow label:red")`
will be better, and worked well

1) https://developers.trello.com/reference/#search
> #label
> Returns labeled cards. **label:** also works.

2) I think #label broke request url.

**Comment by gregsdennis** [comment]
@LeXX is this still an issue for you?  It sounds like you need to refresh your token.  The URL you use to create the token has an expiry in it.  There is an option to have it never expire, but I'd advise against that for security reasons.

Please see https://developers.trello.com/v1.0/page/authorization for more information on authorization.
