### ISSUE TITLE
CardFilter.Visible -  invalid value for filter

### ISSUE THREAD

**Issue by mathieuchateau** [gregsdennis/Manatee.Trello#109]
Hello,

looks like CardFilter.Visible is not a valid filter, at least now.

Open and All filters are working fine.

Trello reported an error: 'invalid value for filter'

************** Texte de l'exception **************
System.Net.Http.HttpRequestException: Trello reported an error: 'invalid value for filter'
   at Manatee.Trello.Internal.ExceptionHandling.DebugLog.Error(Exception e, Boolean shouldThrow) in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\Internal\ExceptionHandling\DebugLog.cs:line 26
   at Manatee.Trello.Internal.DataAccess.JsonRepository.ValidateResponse(IRestRequest request) in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\Internal\DataAccess\JsonRepository.cs:line 64
   at Manatee.Trello.Internal.DataAccess.JsonRepository.Execute[T](TrelloAuthorization auth, Endpoint endpoint, IDictionary`2 parameters) in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\Internal\DataAccess\JsonRepository.cs:line 29
   at Manatee.Trello.ReadOnlyCardCollection.Update() in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\CardCollection.cs:line 64
   at Manatee.Trello.ReadOnlyCollection`1.GetEnumerator() in C:\Users\gregd\Desktop\Manatee.Trello\Manatee.Trello\ReadOnlyCollection.cs:line 59
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)

**Comment by mathieuchateau** [comment]
just My fault I guess, need more tests

**Comment by mathieuchateau** [comment]
Cannot work around.

To reproduce : var temp= list.Cards.Filter(CardFilter.Visible).Count();

**Comment by gregsdennis** [comment]
Thank you for the report. I'll look into this.

**Comment by gregsdennis** [comment]
The API says it's still supported.  I can't imagine they'd discontinue support without bumping the API version.

https://developers.trello.com/reference#cards-nested-resource (search for "filter")

**Comment by gregsdennis** [comment]
@mathieuchateau I've been able to replicate the error.  I'm looking into it further.

**Comment by gregsdennis** [comment]
The docs say that `visible` is the default.  Is there a reason you're trying to filter explicitly?

**Comment by mathieuchateau** [comment]
@gregsdennis :
wasn't sure if default was visible or open. I am dumping cards in separate works based on this filter, and so in source code is easier to read if explicit.
While it stays default, your code should then just strip it when doing the call ?

Often, when making default value explicit and so not useful, Jetbrains change color, so it's easy to know being explicit is alreay default. There it's not detecting that visible is already default value.

**Comment by gregsdennis** [comment]
The code doesn't track which parameters are default in the API (except when a selection of properties isn't quite what I want).  I did to keep up with changes if Trello decides to change it.

Regarding default values on enums (which would be picked up by R#), all of the enums have a `None` value that is the "default" value.  This is a common practice with enums to avoid incorrectly setting a valid value.

**Comment by gregsdennis** [comment]
From Trello support:

>We support the filter *filter=visible* for cards only when it is a nested resource in specific other resources. For instance, the filter works if you are getting cards as a nested resource from the board object (/1/boards/{boardID}/cards?filter=visible). However, the list object is not one that supports that. I'm going to update our documentation to explicitly outline which objects do support that filter.
>
>I believe that you could use filter=open instead and get the same expected outcome. Let me know if that doesn't do the trick for you!

It seems odd to me that they'd support `visible` on boards but not lists.  I'll have to update to catch this special case.

**Comment by gregsdennis** [comment]
When I asked about the inconsistent behavior, they replied:

> Unfortunately, I don't have a good answer as to why we've ended up with inconsistent behavior. However, I've added this to our backlog and hopefully we'll get it fixed sometime in the future. Going forward, we'll likely lean into cards=open. Sorry for the confusion!
