### ISSUE TITLE
new Card() on deleted card

### ISSUE THREAD

**Issue by mathieuchateau** [gregsdennis/Manatee.Trello#112]
Hello,

Not sure where fault is between my code and Manatee.Trello.

How to reproduce:

- Create card in Trello web interface.
- Store Card.Id in your code
- Edit card, then click on Archive and then on Delete

Now try to get card giving card id stored

`var card = New Card(storedCardId);`

It should throw exception, but it does not
If trying to get card.ShorUrl, code hangs indefinitely

**Comment by gregsdennis** [comment]
I'll look into this one.  I would expect that it would throw some manner of "not found" exception when attempting to access the `card.ShortUrl` property.

**Comment by mathieuchateau** [comment]
I expect New Card Method to throw exception like it does if I pass a fully non existing card or board Id.
Even before requesting attribute.
Behavior is just not the one expected if the card existed but was archived + deleted

**Comment by gregsdennis** [comment]
There *is* some checking I can do upon creation to validate it, but I can't check everything.  The long ID is a MongoDB timestamp-based ID, so I can validate that (it's also how I get the creation date).  However, I can't do anything beyond that without making a call.

**Comment by mathieuchateau** [comment]
If I do:
` var test = New Card("NOTEXISTINGENTRY");`
It generates an exception, which I catch. This is how I test if a card exists.

Now, If I do the same on card that existed in the past (so I stored Id), but then was deleted by user, exception is not generated. Maybe Trello API is not providing same answer if Id was walid before?

**Comment by gregsdennis** [comment]
That's because your ID isn't valid. My validation catches that.  But when you use an ID from a deleted card, it passes my validation, the only way I can determine if the card is present is by attempting to download. At that point, and exception is thrown (based on my testing).

**Comment by mathieuchateau** [comment]
ok so in my test I need to also get a property to be sure it does exist, but not shortUrl as it hangs indefinitely ?

**Comment by gregsdennis** [comment]
I wasn't getting the hang in my tests. I'm not certain what is causing that for you.

**Comment by gregsdennis** [comment]
@mathieuchateau are you still experiencing problems with this?

**Comment by mathieuchateau** [comment]
Hello,

It's not hanging anymore, and does generate an exception "requested resource not found", which is what I expected.

I guess we can close this case, thanks
