### ISSUE TITLE
How to use Manatee Objects for Unit Testing

### ISSUE THREAD

**Issue by santiago-russo** [gregsdennis/Manatee.Trello#115]
I have some behavior that requires a specific card and list to be created. As I am writing a unit test for that piece of code, I do not want to connect to a real Trello board, just read some data from the dummy objects I have created in the test.

```csharp
        public void StoryCreation() {
            Card c = new Card("1");
            c.Name = "Hola";
            List l = new Manatee.Trello.List("2");
            l.Name = "To Do";
            c.List = l;
            c.Comments.Add("Hola");
            c.Comments.Add("plus! @santy 0/3");
            c.Comments.Add("Gil");

            Story s = new Story(c);
            Assert.AreEqual(s.StoryPoints, 3);
            Assert.AreEqual(s.SpentStoryPoints, 0);
            Assert.AreEqual(s.IsDone, false);
        }
```

My question here is, how can I create a new List and a New Card in the given example? As the above code is throwing an exception when creating the List.

Regards

**Comment by gregsdennis** [comment]
If you don't want Manatee.Trello to contact the API, you can write your own implementation of `IRestClientProvider` that simply looks at your own store of objects.  Then you need to set `TrelloConfiguration.RestClientProvider`, and you should be good to go.

In your implementation, you'll need to examine the request to determine which object to return.  Or you can use mocks to always return specified objects.

The objects you'll need to return are JSON strings that conform to the interfaces in the `Json` subnamespace.  Feel free to use whatever serializer you want (you already have Manatee.Json referenced).  Just create a POCO and serialize it.  If you have trouble with any particular properties, you can use fiddler to see what's actually being received from the API.

As long as you continue to use the serializer in Manatee.Trello.ManateeJson you shouldn't have to worry about deserialization.

**Comment by gregsdennis** [comment]
Sorry, I had a lapse in understanding.  You want to mock objects like `Card` and `Board`.

This is not supported, but it's an excellent feature idea.

I'll mark this down as a feature.

**Comment by gregsdennis** [comment]
Thinking on this a while, I see three viable possibilities:

1. Create interfaces for all entities and collections.
2. Create a new library in which I can expose internal behavior that allows shortcutting the API calls.
3. Make everything virtual on all entities and collections.

I'm leaning toward option 3 right now...

**Comment by gregsdennis** [comment]
So this works when I make `Card.Name` virtual:

```csharp
[TestFixture]
public class Class1
{
	[OneTimeSetUp]
	public void Setup()
	{
		var jsonFactory = new Mock<IJsonFactory>();
		jsonFactory.Setup(f => f.Create<IJsonCard>())
			        .Returns(() => new Mock<IJsonCard>().Object);

		TrelloConfiguration.JsonFactory = jsonFactory.Object;
	}

	[Test]
	public void Test()
	{
		var mockCard = new Mock<Card>(string.Empty, null);

		mockCard.SetupGet(c => c.Name).Returns("a new name");

		Assert.AreEqual("a new name", mockCard.Object.Name);
	}
}
```

After this, it's probably pretty simple to create a library that handles the initialization stuff.  I might even be able to set up a mock card class.

```csharp
public class MockCard : Mock<Card>
{
    public MockCard()
        : base(string.Empty, null)
    {
        // set up all entity properties to lazily return mocks
    }
}
```
@santiago-russo would something like this help you?

**Comment by gregsdennis** [comment]
Please see branch **feature/115-mocked-entities**.

**Comment by gregsdennis** [comment]
So far, the main thing I don't like about this approach is that I have to create public constructors for everything.

**Comment by gregsdennis** [comment]
I've completed the card mock.  Each of the mock entities will expose mocks for the entities properties.  For instance `CardMock.List` is a `ListMock`.  In this way, you can be sure that you're setting up the right mock objects.

**Comment by gregsdennis** [comment]
I have a few more mocks completed, but I realized something this morning: these mocks aren't going to help if they can't be replaced by the mocks in the code.  To illustrate this:

```csharp
var card = new Card("someId");
```

Because I'm instantiating a card here, there's no way for me to instead create a mock.  I need a factory of some sort.  This leads me to think that creating interfaces (option 1 above) is likely the better solution.

Then I can also create a factory class with methods that match the constructors of each of the entities.

This also has the benefit of not having to make everything virtual and create public constructors just to support Moq.

**Comment by gregsdennis** [comment]
I have completed an initial attempt at interfacing everything.  Please see branch **feature/115-interfaces**.  This will definitely be a breaking change.

**Comment by gregsdennis** [comment]
Okay.  I have the interface version completed on the branch listed above.

@santiago-russo if you can, please clone this branch and see if it works for your needs.  I'd prefer to make changes now rather than before publishing another breaking change.

**Comment by gregsdennis** [comment]
@santiago-russo is this a feature you still need?

**Comment by gregsdennis** [comment]
I'm going to leave this open until I see more of a need to publish a breaking change.  If others would like this feature, please feel free to vote for it using reactions or adding a comment.

**Comment by erikdietrich** [comment]
Hi there.  I did a bit of exploratory playing with Manatee a month or two ago and am now looking to move forward using it.  As someone that's all-TDD, all the time, I would most definitely appreciate a testable API.

As it is, I'm looking at either using a heavyweight isolation tool or writing wrappers around the existing API, neither of which I'm overly excited about.  I don't know if it helps you with your design any, but the wrappers I'd throw over the API would basically get me out of the business of dealing with rich object hierarchies and feature a service with conceptual actions:

```
public Interface TrelloService 
{
  void AddCardWithName(string boardName, string listName, string name);

  void DeleteCardWithName(string boardName, string listName, string name);

  void CreateListWithNameOnBoard(string boardName, string listName);
}
```

I'd then hide the Card/List/Board object hierarchy below this wrapper, which would give me a seam for testing.  I mention this only because it might be an idea for a lightweight API that doesn't mess with the existing rich model, but gives unit test-minded consumers a way to use it.

**Comment by gregsdennis** [comment]
Yeah, that's what I'd expect you'd have to do.  Thanks for reporting your findings.

I've marked this for v3 since it is a breaking change.  I have a bunch of other ideas that I'm trying to get in as well.  Feel free to peruse the milestone.

**Comment by erikdietrich** [comment]
I'll stay tuned, thanks.  

I haven't looked at the source really, but another thing that strikes me as potentially helpful with testing would be to have default constructors for the domain concepts like Board/Card/etc that didn't trigger any web service logic.  Meaning, if I could instantiate a Board, add some Cards to it, and test that way, I'd be good.  Don't know if that's feasible, though.

Anyway, I love the API and it's a big help.

**Comment by gregsdennis** [comment]
I see where you're going with that idea, but I think providing interfaces that can be mocked is the more proper way to do this.
