### ISSUE TITLE
Working with Card-Attachments

### ISSUE THREAD

**Issue by JAYDEV-DE** [gregsdennis/Manatee.Trello#122]
Hey, 

I need some support with the "Attachment" object. 

I want to do the following two things: 

1.) Get attachments of a card 
It seems easy to access the attachments by using „Card.Attachment“, but these objects contain just the information about the file/link. I want the object itself and currently I have no idea if this is even possible.
The API document by Trello (https://developers.trello.com/reference#attachments) shows a list of available fields. One of the fields is called „url“ and the example on the Trello-API site provides a link to the attachment. 
So, what should this link property provide? All my tests just return an empty string. Am I missing/misunderstanding something?

2.) Set an attachment/link
This seems more to be an issue. The Trello API just aborts when trying to set up a Link-Attachment to a card…. But maybe I am just to confused with the attachment topic 😉

Sample-Code:
`var serializer = new ManateeSerializer();
            TrelloConfiguration.Serializer = serializer;
            TrelloConfiguration.Deserializer = serializer;
            TrelloConfiguration.JsonFactory = new ManateeFactory();
            TrelloConfiguration.RestClientProvider = new WebApiClientProvider();
            TrelloAuthorization.Default.AppKey = "";
            TrelloAuthorization.Default.UserToken = "";

            Member MainUser = new Member("");
            Board myBoard = MainUser.Boards.FirstOrDefault();
            Card myCard = myBoard.Cards.FirstOrDefault();
            myCard.Attachments.Add("http://www.google.de", "Test");`

Thanks for the support !

Greetings 

Julian

**Comment by gregsdennis** [comment]
I'll run some testing locally and see what I can find for you. (I really need to get some automated tests built 😉 )

**Comment by gregsdennis** [comment]
@JAYDEV-DE regarding the first item, I'm not sure what the issue is. Are you having trouble downloading the attachment? Is the URL missing? Or do you think that the `Attachment` object should download it for you?

**Comment by gregsdennis** [comment]
@JAYDEV-DE this is a typo internally.  The request to return the attachment URL is actually requesting the `uri`.

I'll have an update to Nuget soon.

**Comment by gregsdennis** [comment]
Manatee.Trello v2.0.1 is publishing.

**Comment by JAYDEV-DE** [comment]
@gregsdennis  ... just wow... I’m impressed with your passion for this project. I really love the speed and the quality of your work, especially on (my) issue requests.

Just for clarification:
Is this project a spare time project or part of your full-time job? If there is no income from this project I would love to donate a few bucks to support your awesome work.

**Comment by JAYDEV-DE** [comment]
@gregsdennis  

I tested the v.2.0.1 and the URL fills correctly, thanks. 

So, now I can download the file, perfect! - But the MIME-Type seems to be empty all the time. This is a problem because without the mime-type I can’t safely figure out what kind of file I am downloading. 
I tested PNG, PPTX and JPG files. None of these files showed any string in the „Attachment.MimeType“-Property. 

Beside from this I have still a problem adding an URL-Link (through the Attachmant.Add()-Function). Sadly, I don’t get any error-message to show, but I hope it can be reproduced easily. 

`Card.Attachments.Add("http://www.google.de",` "Test");`

Greetings

Julian

**Comment by gregsdennis** [comment]
I'll have a look at the MIME type and the add issue.

I develop this in my own time.  It started to support a need for a previous company, but since I did this portion on my own time, it's mine 😄.  If you feel compelled to donate something, I'd be grateful to receive some funding through my PayPal account (use my GitHub username at yahoo) until I can get a donation button on the readme.  Apparently pledgie is shutting down.

**Comment by gregsdennis** [comment]
Regarding the MIME type, it looks like I'm getting `null` back from Trello for picture that I've attached.  Can you give me an attachment ID (email is fine if you're concerned about security)?  Meanwhile I'll email Trello to get their story.

**Comment by gregsdennis** [comment]
I did find a bug in the webapi project that throws an error whenever attempting to POST without a body (all data in URL params).  I'll put out an update soon.

**Comment by gregsdennis** [comment]
@JAYDEV-DE please download Manatee.Trello.WebApi v2.0.2 for the attachment submission issue.

**Comment by gregsdennis** [comment]
I got a response from Trello.  They say that the MIME type is only returned when the request that was used to create the attachment included it.  The web client doesn't include that field when adding attachments, so when you're downloading an attachment that was added online, the MIME type will always be null.

**Comment by JAYDEV-DE** [comment]
Thanks, everything works fine. you should have received a little donation :-)

**Comment by gregsdennis** [comment]
I did. Thank you. You also inspired my wife to make me put a donate button on my projects. :smile:
