### ISSUE TITLE
CustomFields nuget doesn't support .NET Core

### ISSUE THREAD

**Issue by devinrader** [gregsdennis/Manatee.Trello#123]
As the title says.

    Package 'Manatee.Trello.CustomFields 1.2.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
    Version conflict detected for Manatee.Json. Reference the package directly from the project to resolve this issue.

**Comment by gregsdennis** [comment]
Thanks for reporting this. I thought I had pushed it.

Pushing 2.0.0 now...
