### ISSUE TITLE
How to create a new list ?

### ISSUE THREAD

**Issue by ganga0810** [gregsdennis/Manatee.Trello#124]
Hi, first of all thanks for this great api. How can I create a new list so later cards can be added to it? The name for the list should come from user's input. Is there any examples or documentations for this function? I have many other questions like how to move a card from a list to another, how to update a card and so on? Is there any documentations available besides the wiki?

**Comment by gregsdennis** [comment]
@ganga0810 Thanks for the question.  It's actually really simple.

First, you'll want to get a hold of the board that needs the new list.  You can instantiate the board directly or interate through the `Member.Me.Boards` property.

```csharp
var board = new Board("[board ID]");
```

or

```csharp
var board = Member.Me.Boards.FirstOrDefault(b => b.Name == "whatever");
```

Next, you'll need to access the `Board.Lists` property.  Then you can use the `.Add()` method to create your list.

```csharp
var newList = board.Lists.Add("a new list");
```

Please let me know if that helps or if you need anything else.

**Comment by ganga0810** [comment]
Thanks for the reply. And I have another doubt. Now I can create card based on user inputs and added to the list. Is there any method to get the newly created card's id so I can store it in my database and use it in future?

**Comment by gregsdennis** [comment]
The `List.Cards.Add()` method that you used to create the card will return it.  You can get the ID from the `Card.Id` property.

**Comment by ganga0810** [comment]
Thanks for the response.
