### ISSUE TITLE
How to set new list's position?

### ISSUE THREAD

**Issue by ganga0810** [gregsdennis/Manatee.Trello#126]
I want to add a new list after the previous list available in Trello. Something similar like adding card to bottom. How can I set the position of the list when adding it to a board? I can't see any addition parameter that accept position like cards do. 

`var newlist = board.Lists.Add(txtstatus.Text);`

**Comment by gregsdennis** [comment]
@ganga0810 why did you immediately close this?  Did you find the answer you were looking for?

Currently, I don't have the position as a parameter option when creating a list.  The default, however, is for Trello to add the list to the far right (corresponding with `Top`).

I'd be happy to add it as an optional parameter.  Until then you can simply set the position after the list has been created and returned to you.

```csharp
var list = board.Lists.Add("my new list");
list.Position = Position.Top;
```

(This will result in two calls: one to create the list and one to set the position.)
