### ISSUE TITLE
Exception when adding a comment to a card

### ISSUE THREAD

**Issue by Remor61** [gregsdennis/Manatee.Trello#131]
I'm trying to add a comment in a card (actually I tryied other methods with cards and in all of them this error ocurred) and VS acuses the following when reaches in the line:

> Manatee.Trello.Exceptions.TrelloInteractionException: 'Trello has reported an error with the request: The requested resource was not found.'

Here is the code:

`var card = new Card(cardID);
 card.Comments.Add(txtComment.Text);`

the exception happends in the second line

**Comment by gregsdennis** [comment]
Please list the versions of the packages that you have.  I recently released an update to Manatee.Trello.WebApi that fixes POSTing data.

**Comment by Remor61** [comment]
Manatee.Json - 9.7.1
Manatee.Trello - 2.1.0
Manatee.Trello.ManateeJson - 2.0.0
Manatee.Trello.WebApi - 2.0.2
