### ISSUE TITLE
Exception when adding a comment to a card 

### ISSUE THREAD

**Issue by Remor61** [gregsdennis/Manatee.Trello#132]
I'm trying to add a comment in a card (actually I tryied other methods with cards and in all of them this error ocurred) and VS acuses the following when reaches in the line:

Manatee.Trello.Exceptions.TrelloInteractionException: 'Trello has reported an error with the request: The requested resource was not found.'

Here is the code:
```

var card = new Card(cardID);
card.Comments.Add(txtComment.Text);
```

the exception happends in the second line.

using

Manatee.Json - 9.7.1
Manatee.Trello - 2.1.0
Manatee.Trello.ManateeJson - 2.0.0
Manatee.Trello.WebApi - 2.0.2

**Comment by gregsdennis** [comment]
Are you certain the card exists? The card is not actually downloaded in your code, but its ID is used in the create comment call.

**Comment by Remor61** [comment]
Actually now, after I made the logic using the URL's from [here](https://developers.trello.com/reference), I tryied again and it worked. Thanks for answering.

**Comment by gregsdennis** [comment]
Are you using the API directly, or are you still going through the library.

If there's a problem in the code, I'd like to fix it.

**Comment by Remor61** [comment]
Now I'm using your library, except for some delete methods that I couldn't find in the library and in those cases I'm using the API directly

**Comment by gregsdennis** [comment]
Could you list the deletes that you're using?  I'd be happy to add them where I can.
