### ISSUE TITLE
Delete Methods

### ISSUE THREAD

**Issue by Remor61** [gregsdennis/Manatee.Trello#133]
As requested, here is the list of deletes that I'm using that aren't avaliable at the library:

[Delete Card](https://developers.trello.com/reference#delete-card)
[Delete CheckList](https://developers.trello.com/reference#cardsidchecklistsidchecklist)
[Delete Atachment](https://developers.trello.com/reference#cardsidattachmentsidattachment-1)
[Delete CheckList Item](https://developers.trello.com/reference#cardsidcheckitemidcheckitem-2)
[Delete Comment](https://developers.trello.com/reference#cardsidactionsidactioncomments-1)

**Comment by gregsdennis** [comment]
All of these are currently supported via `Delete()` methods on those objects.
