### ISSUE TITLE
DLL Versioning Issue

### ISSUE THREAD

**Issue by erikdietrich** [gregsdennis/Manatee.Trello#137]
Hi there,

First of all, thanks for building this library!  A couple of Nuget installs, and I just successfully popped a card out of Trello and into my console app, and that's a **huge** improvement over other APIs I've had to consume lately.

Just a heads up with your current Nuget package versioning.  To get going, I followed the wiki, installing the Manatee.Trello package (latest) as well as the latest Manatee.Trello.WebApi and Manatee.Trello.ManateeJson.  When I do that, compile your sample, and run in debug mode, this happens:

![image](https://user-images.githubusercontent.com/1232840/36557562-771897ce-17bd-11e8-954b-3c537406fe4d.png)

Using the package manager to 'update' Manatee.Trello to version 2.0.0 sorted it, but I thought you might want to know that, right now, anyone who installs all latest packages will be broken.

**Comment by gregsdennis** [comment]
Thanks for reporting this. I'm not sure what the issue could be.

I'll look into it.

**Comment by gregsdennis** [comment]
When you say you 'updated' to 2.0.0, do you mean you downgraded to a previous Nuget package version?

**Comment by erikdietrich** [comment]
Yes, exactly.  I downgraded using the NuGet version selector.

**Comment by gregsdennis** [comment]
Yeah, nice catch.  I was apparently not thinking when I versioned it.  Look for v2.1.2 to fix the problem.

**Comment by erikdietrich** [comment]
Glad if it helped.  I love the tool, BTW -- gave it a plug on my blog last week.  Thanks for making it!

**Comment by cice** [comment]
Hey, something is still not quite working with the most recent versions (Trello 2.2.0, Json 2.1.0, WebApi 2.0.2):

> CSC : error CS1705: Assembly 'Manatee.Trello.WebApi' with identity 'Manatee.Trello.WebApi, Version=2.0.0.0, Culture=neutral, PublicKeyToken=f7ae00e0424b8d0e' uses 'Manatee.Trello, Version=2.0.1.0, Culture=neutral, PublicKeyToken=f502fcc17fc907d6' which has a higher version than referenced assembly 'Manatee.Trello' with identity 'Manatee.Trello, Version=2.0.0.0, Culture=neutral, PublicKeyToken=f502fcc17fc907d6'

**Comment by gregsdennis** [comment]
Ah. It looks like the other packages were built using the 2.0.1 of Manatee.Trello.

I just need to rebuild and publish the WebApi package.  I'll go ahead and do the JSON usage as well just to be sure.

**Comment by gregsdennis** [comment]
@cice @erikdietrich 
I'll be publishing updated versions of Manatee.Trello.WebApi & Manatee.Trello.ManateeJson shortly.
