### ISSUE TITLE
Manatee.Trello.CustomFields error

### ISSUE THREAD

**Issue by odysseus1973** [gregsdennis/Manatee.Trello#149]
Hello!

Trying to use CustomFields package. When I install and try to compile I get this error

`Error	CS1705	Assembly 'Manatee.Trello.CustomFields' with identity 'Manatee.Trello.CustomFields, Version=2.0.1.0, Culture=neutral, PublicKeyToken=f502fcc17fc907d6' uses 'Manatee.Trello, Version=2.1.0.0, Culture=neutral, PublicKeyToken=f502fcc17fc907d6' which has a higher version than referenced assembly 'Manatee.Trello' with identity 'Manatee.Trello, Version=2.0.0.0, Culture=neutral, PublicKeyToken=f502fcc17fc907d6'	AsnaWebAddIn	C:\Git\AsnaWebAddIn\AsnaWebAddIn\CSC	1	Active`

Thanks

**Comment by gregsdennis** [comment]
Please be sure you have all of the latest packages. I'm fairly certain I resolved this.

**Comment by odysseus1973** [comment]
Yes, all packages is latest versions from Nuget

**Comment by gregsdennis** [comment]
Looks like I neglected to update the custom fields package.  I'll republish that one.

**Comment by odysseus1973** [comment]
Thanks! Waiting for updated package...

**Comment by gregsdennis** [comment]
Having a strange build issue.  Working with Appveyor to sort it out.  Will be with you in a moment... 😄

**Comment by gregsdennis** [comment]
Okay... turns out the build output being in the wiki sub-module to support the autowiki killed the build.

Look for Manatee.Trello v2.3.1 and Manatee.Trello.CustomFields v2.0.2.
