### ISSUE TITLE
Manatee.Trello.CustomFields CustomFields() return null

### ISSUE THREAD

**Issue by odysseus1973** [gregsdennis/Manatee.Trello#151]
Hello!

When I try to get custom fields for card with 
`var fields = card.CustomFields();`
the fields variable contains null

On this Trello board CustomFields PowerUp installed and some custom fields added. 

Thanks!

**Comment by gregsdennis** [comment]
This may have to do with Trello recently updating the API.

I'll run some tests.

**Comment by odysseus1973** [comment]
Hello!

Sorry, this is my mistake. Not all cards on board contain filled custom fields. I must check fields variable for null.

Some custom fields is dropdown list. How to work with this type of fields?

Thanks

**Comment by gregsdennis** [comment]
There is an extension method for `Board` that retrieves the custom field settings.  This will have a list of the available fields.  If one of the fields is a dropdown, then the field definition in this list will specify the options for the dropdown.

When you get the field data from the card, the `Value` property is the selected item.

**Comment by odysseus1973** [comment]
> When you get the field data from the card, the Value property is the selected item.
When I try to get Value of custom field I receive only id of selected item, not text as I thought. How to get text of selected item?

**Comment by gregsdennis** [comment]
So it looks like with the current implementation, the `Value` property will give you the index of the selected value.  You'll have to match that back to the available values (obtained through the board).

Until I update to the new API (#147), I think this is your best option.

**Comment by odysseus1973** [comment]
Hello!

Thanks! Can I get all values of custom fields with one call? Can I get all values of custom fields with one call? Or should I make a request for each card? I have about 500 cards and receiving custom fields takes a long time.

**Comment by odysseus1973** [comment]
Maybe this url can help? https://api.trello.com/1/boards/5a00adcebe1991022b4a4bb4/?fields=name&cards=visible&card_fields=name&customFields=true&card_customFieldItems=true&key={APIKey}&token={APIToken}

**Comment by gregsdennis** [comment]
Yes... This is the new CustomFields API that's been released all of 10 days.  I have #147 for that.

**Comment by gregsdennis** [comment]
So it looks like with the new API, they broke the old one.

From user **bentley-trello** on the Trello Community Slack:

> Custom Field data is no longer stored in /pluginData - and hasn’t been for at least two weeks now. One of the reasons we’re trying to get better about letting you know about changes _before_ they go live.

Looks like I have to get going on updating the custom fields lib.
