### ISSUE TITLE
Reusing HttpClient

### ISSUE THREAD

**Issue by odysseus1973** [gregsdennis/Manatee.Trello#158]
Hello!

Sorry, I may be wrong, but you create a new HttpClient each time. Can it be better to use one HttpClient for all requests?

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/
https://blogs.msdn.microsoft.com/shacorn/2016/10/21/best-practices-for-using-httpclient-on-services/

Thanks!

**Comment by gregsdennis** [comment]
Interesting... I actually asked this as a [question on SO](https://stackoverflow.com/q/26413129/878701) when I was writing it.  Since then it looks like the consensus has changed.

Simple update.  Thanks for point it out.
