### ISSUE TITLE
Consolidate the libraries

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/Manatee.Trello#159]
The entire purpose of splitting the libraries was to create a seam for people to introduce their own implementations for these components.  However, the current implementation does require that the client download three separate libraries.

This change will merge the four existing libraries into one, yet leave the seam available for anyone who cares to use their own implementation.

**Comment by dmirmilshteyn** [comment]
Maybe consider making a metapackage like `Manatee.Trello.All` which only references the base packages needed to quickly get started? The other libraries will then be pulled into target projects automatically.

**Comment by gregsdennis** [comment]
That's one possibility, but consolidation has the advantage of out-of-the-box functionality.  It would do all of the configuration internally allowing you to download and run with it.
