### ISSUE TITLE
Board Labels Limit crash

### ISSUE THREAD

**Issue by rolsct** [gregsdennis/Manatee.Trello#177]
Hi Greg,

First of all, many thanks for your great work : it allows me to manage our entire team workflow on Trello, it is a life saviour for us.

I've a encountered some issues (our boards are quite large and the processing is heavy for now), and found workaround for most of them. But I'm quite stuck with the Labels on Board, with v2.4 : The default limit is 50. But, if I try to increase the board cards collection limit using the Limit extension method, it's returning a null collection, in any case.

            var lstBoardLabels = refBoard.Labels.Filter(100);

            // CRASH : lstBoardLabels is null.
            int nCount = lstBoardLabels.Count();

Any idea ?

Regards,
Roland TOMCZAK

**Comment by gregsdennis** [comment]
Thanks for reporting this.  I'll try to work on this soon.

**Comment by gregsdennis** [comment]
@rolsct [here](https://github.com/gregsdennis/Manatee.Trello/blob/master/Manatee.Trello/Extensions/CollectionExtensions.cs#L121) is the extension method that adds a filter to the label collection on a board.  As you can see, it *can't* return null.

Please run your test again and verify that your `lstBoardLabels` variable is null.  It could be that something inside Manatee.Trello is throwing the exception instead.  If you can, please post the stacktrace.

**Comment by rolsct** [comment]
Sorry, I made a typo when writing my snippet : 

It was not 

var lstBoardLabels = refBoard.Labels.Filter(100); 

but of course

var lstBoardLabels = refBoard.Labels.Limit(100);

I retried it again just right now, on a small board, same  crash from my side (Limit returns null).

Thanks,

Roland

**Comment by gregsdennis** [comment]
That code is [here](https://github.com/gregsdennis/Manatee.Trello/blob/master/Manatee.Trello/Extensions/CollectionExtensions.cs#L295).  Again, it returns a new collection.

**Comment by rolsct** [comment]
Dear Gregs, yes I was still encountering the issue (and, looking as the code as you did, I didn't understand how it could happened :( ). So finally we called directly the REST API to get the full board data. Doing so, we bypass the limit, and we gained in perf to initialize our internal model. As a suggestion, it could be a good option for Manatee.Trello to read the entire content of a Board using the Board GET service, to initialize it and minimize the calls count.

Regards,

Roland

**Comment by gregsdennis** [comment]
I've been able to reproduce this in v3.  It's probably an issue with all collections.  I'll publish an update soon.

**Comment by gregsdennis** [comment]
Trello doesn't list the `limit` parameter in their docs.  I remember seeing it in the old docs (pre-Atlassian).  I'll ask about it.

**Comment by rolsct** [comment]
Thank you Greg !

**Comment by gregsdennis** [comment]
Trello reports that the limit *is* still working.  I'll have to research why I'm not seeing it.

**Comment by gregsdennis** [comment]
So it works in some cases, but not in others.  For example `/1/boards/{id}/cards?limit=1` only returns a single card, but `/1/boards/{id}/lists?limit=1` ignores the parameter and returns all of the lists.

**Comment by gregsdennis** [comment]
@rolsct please watch for v3.0.7.  Should be up soon.
