### ISSUE TITLE
JetBrains.Annotations

### ISSUE THREAD

**Issue by TimSirmovics** [gregsdennis/Manatee.Trello#179]
Can the classes within the JetBrains.Annotations namespace be made internal?

The reason I ask is that once I bring the Manatee.Trello assembly into my solution, R# thinks that it can use these classes and starts decorating the attributes in places where I use R# quick fixes.

Having a look at other libraries that include their JetBrains annotations in the same way, it appears they make the classes internal which prevents this.

**Comment by gregsdennis** [comment]
Making it public was actually the desired behavior.  However, due to the changes in the upcoming v3, I have no more use for them, so I deleted the annotations completely.

I'll also look at the usages in v2 to see what I can do there.

**Comment by gregsdennis** [comment]
I have v3 available now, if you want to give that a go...

**Comment by TimSirmovics** [comment]
Yep thanks!
