### ISSUE TITLE
Initial setting of custom field value on a card

### ISSUE THREAD

**Issue by TimSirmovics** [gregsdennis/Manatee.Trello#188]
How do I set the value of a custom field on a card, before it has a value?

I am creating a new card, and want to set some of the custom field values that are already defined for the board.

None of the `ICardCollection.Add()` overloads allow passing in a custom field collection, so I thought I would set it after the card has been created.
After the card is created, the `ICard.CustomFields` property does not contain any items, since they have no value (consistent with the [API docs](https://developers.trello.com/v1.0/docs/getting-started-custom-fields#section-getting-customfielditems-for-cards)), however as this is an `IReadOnlyCollection` I can't add a custom field.

**Comment by gregsdennis** [comment]
Yeah, that one was kind of hard to implement.  Trello doesn't consider the field to exist on a card if it doesn't have a value.  So to set the value, you have to go to through the board to get the definition.

```csharp
var fieldDef = board.CustomFields.FirstOrDefault(f => f.Name == "my custom field"); // or whatever
var field = field.SetValueForCard(card, 9);
```

There is a `SetValueForCard()` overload for each of the field types.  Make sure you use the right one.

Also, know that I don't have a way to turn on custom fields for a board yet.  I don't think Trello's enabled that through the API.  You'll have to ensure the Custom Fields Power Up is enabled manually.

I'm still working on the docs, so I'll make sure this gets in there.

**Comment by TimSirmovics** [comment]
Cheers for the info Greg, all sorted now.

**Comment by agross** [comment]
Hm, I cannot get this working. The custom field is found, but the value is not visible on Trello web. I tried both variants:

```cs
await board.CustomFields.Refresh();

var fieldDef = board.CustomFields.FirstOrDefault(f => f.Name == "Test");
var field = await fieldDef.SetValueForCard(card, "foo");

var fieldDef2 = card.CustomFields.FirstOrDefault(f => f.Definition.Name == "Test");
await fieldDef2.Definition.SetValueForCard(card, "bar");
```

Request logs:
```
Get boards/565c9b92aa7b1f3d0c40c8c2/customFields

Status Code: OK (200)
[
  /* elided... */
  {
    "id": "5af57fdf27cd99abcfc18682",
    "idModel": "565c9b92aa7b1f3d0c40c8c2",
    "modelType": "board",
    "fieldGroup": "db9abbe08d29978e3081a94dd24adfb7432161acee8c873231cd9feb60904a52",
    "display": {
      "cardFront": true
    },
    "name": "Test",
    "pos": 98304,
    "type": "text"
  }
]

Sending: Put card/5af58094ae5c1cab41307097/customField/5af57fdf27cd99abcfc18682/item

Status Code: OK (200)
{
  "id": "5af580a027d1a782ad24bf1b",
  "value": null,                                                 /* value == null? */
  "idCustomField": "5af57fdf27cd99abcfc18682",
  "idModel": "5af58094ae5c1cab41307097",
  "modelType": "card"
}
```

**Comment by agross** [comment]
Regarding setting a `string`, could [this line](https://github.com/gregsdennis/Manatee.Trello/blob/master/Manatee.Trello/Internal/Synchronization/CustomFieldDefinitionContext.cs#L155) be the issue?

**Comment by agross** [comment]
Just tried with a field type of number, that seems to work.

**Comment by gregsdennis** [comment]
Yeah... that seems like a problem. :)

**Comment by gregsdennis** [comment]
@agross watch for v3.0.7.  That should fix the issue.
