### ISSUE TITLE
 Trello PowerUps Platform

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/Manatee.Trello#19]
Trello introduced a way for people to create their own power ups.

https://developers.trello.com/power-ups/intro

Should probably look into it.

**Comment by gregsdennis** [comment]
Looks like power-ups are now available for free users!

https://blog.trello.com/trello-power-ups-for-all/?utm_source=inapp&utm_medium=link&utm_campaign=powerupsforall

**Comment by gregsdennis** [comment]
Looking at the implementation, this may have to be another library (or series of libraries) that expose and disseminate each plug-in.

This is related to #38.

**Comment by gregsdennis** [comment]
See branch feature/power-ups.

**Comment by ronwarner** [comment]
@gregsdennis - In reference to [#38](https://github.com/gregsdennis/Manatee.Trello/issues/38) on the main branch...

I'm curious if you'll need to implement the entire PowerUps Platform before access to Custom Fields will be available.  Is there a ballpark ETA on these features?  The ability to programmatically access the new Custom Fields would be gigantic for me, so I'm excited you're doing it!

**Comment by gregsdennis** [comment]
@ronwarner I'm currently trying to determine a reasonable implementation that's easy to use and works well with the current object model.

There have been some other complications for implementing power-ups in general in that the creator of the power-up can use the fields in the API as they see fit, which means there's no consistency.  I'm leaning toward enabling power-up data access available through the main Nuget pkg, then each power-up will be its own pkg.

I've also been in communication with the Trello API devs, and they're still working on how to implement power-up data through the API properly.  It seems it's still beta-ish.

I don't have an ETA, but I'm continuing to work on it as I have time.

**Comment by gregsdennis** [comment]
Copying Trello support email regarding Power-Ups data

>Hey Greg,

>We have a bit more information about data storage for Power-Ups here, under the "Data Storage" section: https://developers.trello.com/power-ups/topics.

>What we currently expose via the API, though readonly at this moment, is: 

>`/1/boards/[id]/pluginData
>`/1/cards/[id]/pluginData

>Those both allow access to the shared visibility data at that scope (boards or cards). Power-Ups can store data on cards at the 'card' scope, or boards, or orgs (teams). Where they choose to store what data is entirely up to the Power-Ups themselves, so accessing the data via the API does require an understanding of how the Power-Up is working.

>I know this may be less than ideal. Data storage for Power-Ups is something that we are currently looking into exposing a bit more of via the API, so hopefully in the future we will be able to standardize this a bit more.

>All the best,

>Mercer
>The Trello Team

**Comment by ronwarner** [comment]
Awesome approach!

**Comment by gregsdennis** [comment]
@ronwarner, please check out Manatee.Trello 1.13.0 and Manatee.Trello.CustomFields.  That should give you read access to the custom field data.
