### ISSUE TITLE
Can't instantiate Board after upgrade to 3.0.2.

### ISSUE THREAD

**Issue by TimSirmovics** [gregsdennis/Manatee.Trello#190]
I just upgraded to 3.0.2 as I was having trouble with 3.0.1 moving a card to a different list, but now I can't instantiate a Board object with an ID.

```
TrelloAuthorization.Default.AppKey = "xxx";
TrelloAuthorization.Default.UserToken = "xxx";

var board = new Board("xxx");
```

> System.AggregateException
>   HResult=0x80131500
>   Message=One or more errors occurred.
>   Source=mscorlib
>   StackTrace:
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at Manatee.Trello.Board.get_Id()
>    at Manatee.Trello.Internal.Caching.ConcurrentCache.Add(ICacheable obj)
>    at Manatee.Trello.Board..ctor(String id, TrelloAuthorization auth)
>    at .....
> 
> Inner Exception 1:
> ArgumentNullException: Value cannot be null.
> Parameter name: key
>

**Comment by gregsdennis** [comment]
Yep... That's the problem.  I'll put out a 3.0.3 soon to fix this.

**Comment by TimSirmovics** [comment]
Upgraded to 3.0.3 however i'm unfortunately still getting the same exception.

**Comment by gregsdennis** [comment]
I'm not getting the error.  I can instantiate a board with the current [dev test](https://github.com/gregsdennis/Manatee.Trello/blob/88829a7b8a7b35b300be981ff14f069882267940/Manatee.Trello.UnitTests/DevTest.cs).
