### ISSUE TITLE
Deadlock when using library from ASP.NET

### ISSUE THREAD

**Issue by TimSirmovics** [gregsdennis/Manatee.Trello#197]
I have managed to mostly avoid the Asynchronous programming model up until using this library, so I am not a natural with it, and I have come across an issue I can't seem to solve.

We are using Manatee.Trello from an ASP.NET MVC application.

During development, all of the library functions were executed from test runners which worked. Once we started testing from the MVC project, any async call to the libary would hang.

We were only interested in using the libary synchronously, so any call to an async method like `Refresh()` was followed with a `.Wait()`. This worked fine from a test runner, but as soon as we were executing from ASP.NET the code would hang. Several SO posts led me to [this blog post](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) which recommended not blocking with `.Result` or `.Wait()`, but instead using await all the way back up to the top level calling method.

We tested this, but found that we were still hanging on the `Board()` constructor. Stepping into the code reveals that the line the app was hanging in was in the `Id` property getter, where there is an embedded wait `this._context.Synchronize(CancellationToken.None).Wait();`.

I think, according to the previously referenced blog post this is causing our issue as all calls down the chain need to be awaited.

To recreate this, create a new ASP.NET MVC project (We are using .NET Framework 4.7), add the Manatee.Trello library to it, and create a controller action that tries to construct a board with an ID. The constructor call does not return.

**Comment by TimSirmovics** [comment]
I have found a workaround for this for the moment, for any calls that will eventually call the Manatee.Trello library from a controller I use `Task.Run()` which puts the work on the Thread Pool avoiding any deadlocks with the ASP.NET request context thread.

**Comment by gregsdennis** [comment]
How are you instantiating your board?  My guess is that you're using the short ID.  Would it be possible to use the full ID?
