### ISSUE TITLE
Canceled request: Unable to create a secure SSL / TLS channel.

### ISSUE THREAD

**Issue by Caloyski** [gregsdennis/Manatee.Trello#214]
The application I made suddenly stopped working. 
I debugged and it stops when I create a new instance of Board

`var board = new Board(_trelloBoard);`

The error is the following
Canceled request: Unable to create a secure SSL / TLS channel.

The application ran as expected for several months, until a few weeks ago.

**Comment by Caloyski** [comment]
My bad. Thank you!

**Comment by gregsdennis** [comment]
No worries. Thanks for using my library!
