### ISSUE TITLE
Copy a checklist from existing card

### ISSUE THREAD

**Issue by imran-uk** [gregsdennis/Manatee.Trello#215]
We keep a "template card" in our of our Trello lists. This card has the function of acting like a template by holding a big checklist which we can copy/paste into newly added cards.

What I want to do is automatically create a new card and then copy the checklist items from my "template card" to it. I've got the automatic card creation bit donw but I can't figure out exactly how to get at the checklist from the template card to put into my new card. 

Can someone please give me some pointers? Is "copy card" the best way? I've got lost in the maze of methods/properties with regards to the Checklist and CheckListCollection classes. 

Thank you!

**Comment by imran-uk** [comment]
Sorry, I was not sure how to add the "help wanted" label as the "Labels" section seems greyed out for me.

**Comment by gregsdennis** [comment]
The *help wanted* label is for me to ask for your help.  Also, only I can label and assign issues.

I'll try to have a look at this today. I don't think I have a test for copying a checklist.

**Comment by gregsdennis** [comment]
I've added a [test](https://github.com/gregsdennis/Manatee.Trello/blob/master/Manatee.Trello.IntegrationTests/CheckListTests.cs#L46) to verify copying checklists from one card to another.  It passes fine.

Can you post the code that's failing for you?

**Comment by imran-uk** [comment]
Many thanks for the quick reply @gregsdennis - we didn't get as far as writing code because of said confusion over exactly how to go about it.

Would you be kind enough to maybe add here or to the Card API docs to demonstrate how I would copy checklist only from one card to another?

Thanks again

**Comment by gregsdennis** [comment]
As it happens, I've just (finally) been able to get the [github pages](https://gregsdennis.github.io/Manatee.Trello/) site working!  Check it out!

If you checkout the test that I linked to in my previous comment, it does precisely what you're asking.

**Comment by imran-uk** [comment]
Thanks @gregsdennis new docs page look really good.

I've been taking steps to duplicate the "template card" and just re-name it. So far looks OK but I think I'm running into some async issues when I set the name property on the new card, it seems to work intermittently:

```
var templateCard = factory.Card("<id>");

Task.Run(async () =>
{
  await templateCard.Refresh();
}).GetAwaiter().GetResult();
            
if (action == "opened" || action == "reopened")
{
 ICard newCard;

Task.Run(async () => {
  newCard = await list.Cards.Add(templateCard);
  newCard.Name = title;
  newCard.Refresh();
  Console.WriteLine($"dawg, created a Trello card yo: {title}");
}).GetAwaiter().GetResult();
 }
```

**Comment by gregsdennis** [comment]
It could be a bit more explicit, but on the Getting Started page, under [Writing data](https://gregsdennis.github.io/Manatee.Trello/1-main/getting-started/#writing-data) I talk about how writing to properties is asynchronous.  This is done to minimize API calls on a single entity.  If you're done making changes and you want to push those changes, you need to call `await TrelloProcessor.Flush()`.  You can see this at work in my integration tests.

I'll update the docs to include this.

**Comment by imran-uk** [comment]
What good support I'm getting @gregsdennis - thank you!

I did indeed need `await TrelloProcessor.Flush()` to solve my issue.

I can now create cards on my Trello board automagically when someone creates a new pull-request.

I'm now turning my attention to Power-Ups. We use the GitHub Power-Up and what I want to do is automatically "Attach Branch" to the card based on the branch name used to name the card. The Power-Up then syncs info from our GitHuib automatically including state of TeamCity tests etc.

I can see that there appears to be some Power-Up API docs in Manatee.Trello - any pointers would be welcome. It might be that I would need to consult the API that the Power-Up exposes instead.

Thanks again!

**Comment by gregsdennis** [comment]
I'm currently looking at the Power-Up portions of Manatee.Trello to make it easier to build implementations.  Right now, it's all very manual and causes the implementer (you, in this case) to recreate some of the logic I already have done.  I think I'm going to have to expose some of the inner logic in order to alleviate that.

For now, you can follow the [Power-Up page](https://gregsdennis.github.io/Manatee.Trello/1-main/power-ups/).  Just be aware that it will likely change soon.  It shouldn't break anything, but hopefully the newer method will be easier to use.

**Comment by gregsdennis** [comment]
@imran-uk I just noticed that you specifically mentioned the GH plugin. I started to implement that one, but I stopped because it's just attachments.  It's literally attaching a link to the GH issue/PR/branch to the card.  The main "power" is in how the UI renders those attachments.

**Comment by imran-uk** [comment]
@gregsdennis Ah yes, I see you are correct. I added a URL attachment to a card and the Power-Up "just worked".

`newCard.Attachments.Add(pullRequestUrl, title);`
