### ISSUE TITLE
Lists all empty.

### ISSUE THREAD

**Issue by gnaritas** [gregsdennis/Manatee.Trello#216]
My little bot stopped working, so I upgraded my nuGet packages which now look like

  <package id="Manatee.Json" version="9.8.0" targetFramework="net452" />
  <package id="Manatee.Trello" version="3.0.10" targetFramework="net452" />
  <package id="System.ValueTuple" version="4.4.0" targetFramework="net452" />

On .Net version 4.5.2.

I don't get any errors, but nothing works because all my boards come back with empty Lists.

var board = new Board(DEVELOPMENT_BOARD);
board.Lists <= is now empty

Seems like it's not even hitting Trello anymore, the program starts and finishes too fast for any API calls to be happening. Help.

**Comment by gregsdennis** [comment]
Version 3+ relies on the client (that's you) to manage refreshing data.  This was done as part of adopting an async/await model.

Please see the [documentation](https://github.com/gregsdennis/Manatee.Trello/tree/master/docs).

**Comment by gnaritas** [comment]
Wow, this has made using your API synchronously quite messy.  I'm going to have to sprinkle Refresh().Wait()'s and Add().Wait()'s all over the place.  You've just broken my entire program, for what... to use async/await that most programs like this simply don't require as they're background processes.  Is this really my only option now, to litter my program with refreshes and waits?

**Comment by gnaritas** [comment]
Additionally, I want to buy a license, but your link to your license page doesn't work.  Why won't you take my money? ;)

**Comment by gnaritas** [comment]
> The async/await pattern is pretty much now standard for .Net applications

I'd push back on that and say it's the standard for when you need asynchronous code; i.e. an option, it shouldn't be looked upon as the only solution.  Synchronous code is and will always remain the norm for  most code doesn't need to be threaded.

It's your lib, do as you wish, but you're forcing a paradigm on people due to fashion, not need, and that's going to reduce your user base.  Just because something can be async, doesn't mean it should be async.

**Comment by gnaritas** [comment]
And your license link is still broken. Not in the docs folder.  It's very hard to give you money man.

**Comment by gnaritas** [comment]
OK, so lets get to the money.  The link in your docs says

https://github.com/gregsdennis/Manatee.Trello/blob/master/docs/licensing.md

That's still a 404.  Can you just give me a direct link to somewhere I can buy a license, this 300 request limit is killing me.
