### ISSUE TITLE
Can't connect 

### ISSUE THREAD

**Issue by morrfo** [gregsdennis/Manatee.Trello#220]
Hi gregsdennis,
    I've been using your libraries more than three years without problems. From 8th of May your library Manatee.Trello started returning following error: "Trello returned with an error. Error Message: Unable to create a secure SSL / TLS channel. Do you know what it can be?
Very thank

**Comment by gregsdennis** [comment]
Yes, Trello made some updates to their TLS requirements.  Please see #200 for details.
