### ISSUE TITLE
Refresh methods hangs with WPF application but not with .Net Core.

### ISSUE THREAD

**Issue by rtrianiguerra** [gregsdennis/Manatee.Trello#243]
**Describe the bug**
**To Reproduce**

Hi! Playing around with your library and cannot figure out why Refresh method hangs when called from WPF app and not from .NET Core app.

I have 3 projects in a soluction: 

* TrelloHelper.Library: A .NET Standard Library (2.0), referencing Manatee.Trello 3.2.1 and dependencies (Json and WebApi)
* TrelloHelper.ConsoleApp: A .NET Core 2.0 Console, referencing TrelloHelper.Library
* TrelloHelper.WinApp: A .NET Framework 4.6.1 WPF Application referencing TrelloHelper.Library

At the TrelloHelper.Library I have a simple method to connect to Trello, get a board and enumerate it's lists. Code bellow:

```
        public void TestTrelloConnection(string output)
        {
            string s;
            var stb = new StringBuilder();
            var factory = new TrelloFactory();
            var board = factory.Board(boardDEV);
             board.Lists.Refresh();

            s = $"Board: {board}";
            stb.AppendLine(s);
            Console.WriteLine(s);
            foreach (var list in board.Lists)
            {
                s = $"   {list}";
                stb.AppendLine(s);
                Console.WriteLine(s);
            }
            stb.AppendLine(s);
            Console.WriteLine();

            s="Connection OK!";
            stb.AppendLine(s);
            Console.WriteLine(s);

            output = s;
        }

```
At the TrelloHelper.ConsoleApp, I have the following code, that works **perfectily**:

```
        static void Main(string[] args)
        {
            string s = "" ;
            TrelloHelperLib.TrelloHelper  tr;
            tr = new TrelloHelperLib.TrelloHelper();
            Console.WriteLine("Connecting to trello...");
            tr.TestTrelloConnection(s);
            Console.WriteLine(s);
            Console.ReadLine();
        }

```

At  TrelloHelper.WinApp, I have a button that calls the following method. But it does not work, hanging at the line "board.Lists.Refresh();" inside the method TestTrelloConnection :

```
        private void btTestarConexao_Click(object sender, RoutedEventArgs e)
        {
            string s = "";
            tr.TestTrelloConnection(s);
            MessageBox.Show(s);
        }
```
**I don't know if it is a bug or if I'm doing something wrong using async/await in WPF Application ...**

**Expected behavior**
I expected that the behavior would be the same at the .net core console and the .net wpf app.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
- .Net Target 4.6.1, Core 2.0 e Standard 2.0 
 - Version: Manatee.Trello 3.2.1, ManateeJson 2.3.0 and Manatee WebApi 2.0.3 (all using .net standard 2.0)
- Visual Studio Community 2017 15.7.3

**Additional Information.**
**Your project is awesome. Thanks!**

**Comment by gregsdennis** [comment]
Thanks for reporting this. I can see that one problem is the async/await usage, but surprised that the console app works.

I'm on my phone right now, though. I'll update later today after I can do some testing.

**Comment by gregsdennis** [comment]
@rtrianiguerra does this help?  Are you still experiencing issues?

**Comment by rtrianiguerra** [comment]
Yes, @gregsdennis! You put me on the track! I've gone back to the C#'s book to review tasks/await/async, strugglered a little, but got it working!

**Thanks a lot!**

Now I'll begin to make something useful to publish on GitHub!

These are the revised methods:

**Library** 

 ```
   public static async Task<string> TestTrelloConnection()
        {
            string s;
            var stb = new StringBuilder();
            var factory = new TrelloFactory();
            var board = factory.Board(boardDEV);
            await board.Lists.Refresh();

            s = $"Board: {board}";
            stb.AppendLine(s);
            foreach (var list in board.Lists)
            {
                s = $"   {list}";
                stb.AppendLine(s);
            }
            stb.AppendLine(s);

            s = "Connection OK!";
            stb.AppendLine(s);

            return stb.ToString();
        }
```

**ConsoleApp**:

```
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Test().Wait();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            Console.ReadLine();
        }

        static private async Task Test()
        {
            Console.WriteLine("Connecting Trello...");
            var s = await TrelloHelperLib.TrelloHelper.TestTrelloConnection();
            Console.WriteLine(s);
        }
  }
```    

**WPFApp** :

```
        private async void btTestarConexao_Click(object sender, RoutedEventArgs e)
        {
            var s = await Task.Run(() =>
                TrelloHelperLib.TrelloHelper.TestTrelloConnection());
            MessageBox.Show(s);
        }

```

**Comment by gregsdennis** [comment]
That's a lot better. Just remember that `async void` should only ever be used for event handlers. Outside of that, you should always return a task.
