### ISSUE TITLE
Example request - Get Member details

### ISSUE THREAD

**Issue by Starigazdam** [gregsdennis/Manatee.Trello#249]
Hello, would you mind create example how to get Member data?

I am failing to get any useful data. For example, in code below, member `creator` is not null, but there are no interesting data (`FullName`, `Initials`,...) , everything is set to null (available are only `Id` and `CreationDate`).

```
var board = new Board(config.BoardId);
 await board.Refresh();

var f = new TrelloFactory();
var card = f.Card(cardId);

await card.Comments.Refresh();
var comment = card.Comments.OrderBy(c => c.CreationDate).LastOrDefault();

await comment.Creator.Refresh();
var creator = comment.Creator;
```
Thank you.

**EDIT:**
I am getting expected result (Member object with loaded data) after commenting out lines in `Manatee.Trello/Manatee.Trello/Internal/Synchronization/MemberContext.cs`, lines `229-258`.

Is this **feature**? Or is the usage in my code snippet correct?

**Comment by gregsdennis** [comment]
Thanks for reporting this.  I'll set up a test to investigate.

**Comment by gregsdennis** [comment]
This is due to another inconsistency in Trello's API.  Whenever they send an entity, they typically return a JSON string when only giving the ID, whereas they use a JSON object when returning any other data.  In this case, as part of the returned action, they're returning a JSON object with only the `id` property populated.

I'm working to account for it.  I should have an update out tonight or tomorrow.

**Comment by nvaghari** [comment]
Is this issue solved? I'm using the latest version of NuGet but can not get the creator for comments

**Comment by gregsdennis** [comment]
Yes, this has been working as of v3.3.1.  I just verified locally.

**Comment by nvaghari** [comment]
I'm using v3.6.0 with this code:
`            var selectedCard = Factory.Card(cardId);
            await selectedCard.Comments.Refresh();
foreach (var comment in selectedCard.Comments)
            {
                var fetchedComment = Factory.Action(comment.Id);
                await fetchedComment.Refresh();
}`
But the fetchedComment.Creator always is Null. I'm using Refresh twice to try more!

**Comment by gregsdennis** [comment]
Please try v3.6.1.  Also v3.7.0 will be available soon.

**Comment by nvaghari** [comment]
I tried hard but there is no hope to get Creator of Comments. last pseudocode:
```
var cm =Factory.Action(comment.TrelloId);
                cm.Refresh();
                comment.By = cm.Creator.FullName;
```

can you help me?

**Comment by gregsdennis** [comment]
I'm not sure what's going on there.  I set up a test, and when I just run the test it fails, but debugging the test it works.  Might be a timing issue somewhere.  I'm continuing to look.

**Comment by nvaghari** [comment]
I hope this issue will be solved. but your framework is too hard to working with it. finally, I wrote my own code and very easy I caught all the comments using official rest API. thank you
