### ISSUE TITLE
Bulk Refresh All Custom Fields of all Cards

### ISSUE THREAD

**Issue by vlaine** [gregsdennis/Manatee.Trello#252]
I would like to get all the cards of a board, including the custom fields.
The Trello Api allows you to do it with a single call.
https://api.trello.com/1/boards/{boardId}/cards?customFieldItems=true&key={key}&token={token}

Currently with Manatee.Trello, I have to loop and refresh Custom Fields for each card.
I hope I missed something.  There must be a better way.
Here's my current code:
```
var board = _factory.Board("*****", _auth);
await board.Refresh();
await board.Cards.Refresh();
board.Cards.ToList().ForEach(c => c.CustomFields.Refresh());
return board;
```

**Comment by gregsdennis** [comment]
I think it can be done with the current implementation.  I'll run some tests.

**Comment by gregsdennis** [comment]
It looks like I add those kinds of parameters when refreshing individual items but not on collections.  I'll have to add in that functionality.

**Comment by gregsdennis** [comment]
I'm classifying this as a bug since I thought it was doing this already.  Update coming soon.

**Comment by gregsdennis** [comment]
Please see v3.3.2

**Comment by vlaine** [comment]
Good job.  No more loop to get CustomFields.  Thanks
```
var board = _factory.Board("*****", _auth);
await board.Refresh();
await board.Cards.Refresh();
return board;
```

**Comment by gregsdennis** [comment]
That's it!
