### ISSUE TITLE
Working with Archived Cards?

### ISSUE THREAD

**Issue by erikdietrich** [gregsdennis/Manatee.Trello#256]
Hi there.

I'm trying to use the Card API's "IsArchived" property to correspond with a property in my codebase called IsApproved.  The logic is simple in terms of what I want to do: if the card is approved, show it, otherwise, archive it.   And I have a workflow that might trigger the card to toggle back and forth in these states.

Problem is, as best I can tell, once I set a card's IsArchived to true, I can't grab it through the board or list objects anymore.  I found in the method header comments that Board.Cards only shows un-archived cards, so it seems that once you flag a card archived, it's kind of forever lost to Manatee.Trello.

Is there a way to grab archived cards?  And, if not, that's my feature request :)

Thanks!

**Comment by gregsdennis** [comment]
The card collection on the `Board` object has `Filter` method that you can use to achieve this. Pass in `CardFilter.All` to get all of the cards when you refresh the collection. This is a permanent change to that collection object, so you'll only need to set it once.

**Comment by erikdietrich** [comment]
That did the trick perfectly.  Thanks for the quick and helpful reply!

**Comment by gregsdennis** [comment]
Sure. And remember, you can also ask questions in Slack. There's a link at the top of the readme.
