### ISSUE TITLE
Filter in cards by date not work

### ISSUE THREAD

**Issue by zodchiy** [gregsdennis/Manatee.Trello#259]
This code:
```
trelloboard.Cards.Filter(DateTime.Now.AddDays(1), DateTime.Now.AddDays(2));
trelloboard.Cards.Refresh().Wait();
```
return a card with yesterday's date.
Edit:
```
trelloboard.Cards.Filter(DateTime.Now.AddDays(1), null);
```
I think the url have a wrong datetime format:
/1/boards/xxx/cards?cards_since=**18.10.2018%2016:50:01**&cards_fields=...

EDIT 2:
I fix this. https://github.com/gregsdennis/Manatee.Trello/pull/260
But problem still exists.

**Comment by gregsdennis** [comment]
I'd like to keep the issue open until the fix is merged.
