### ISSUE TITLE
Getting comments from a card

### ISSUE THREAD

**Issue by Racoon77** [gregsdennis/Manatee.Trello#275]
Hi,
I was wondering if you could tell me what I'm doing wrong. I'm trying to read all comments, to get the raw text from them and even though I tried several approaches, I can't get comments from a card. The collection simply appears empty.
This is the method I use:
```csharp
public async Task<List<(DateTime CreationDate, string Text)>> GetRawComments(string listName, params string[] cardNames)
{            
    IMe me = await Factory.Me();
    IBoard board = me.Boards.Single(b => b.Name == BoardName);
    await board.Refresh();
    IList list = board.Lists.Single(l => l.Name == listName);
    await list.Refresh();
    List<ICard> cards = list.Cards.Where(c => cardNames.Any(name => c.Name.Contains(name))).ToList();

    var comments = new List<(DateTime CreationDate, string Text)>();
    foreach (ICard card in cards)
    {
        await card.Refresh();                                
        foreach (IAction comment in card.Comments) // card.Comments is empty
        {
            DateTime creationDate = comment.CreationDate;
            string text = comment.Data.Text;
            comments.Add((creationDate, text));
        }
    }            
    return comments;
```
Everything up until the comments is loaded fine, but the ```card.Comments``` collection is empty, so the foreach block isn't even executed, even though it should contain few hundreds of comments.
I configure Trello credentials in the constructor, and since it loads the cards just fine, I assume that part is probably fine.

**Comment by gregsdennis** [comment]
One of the things I dislike about the Trello API is that they model comments as actions. This means that I can't download both actions and comments in the same call.

By default, I set up cards to download with actions, so you'll need to change that using the `Card.DownloadedFields` static property.

```csharp
Card.DownloadedFields &= Card.Fields.Actions;
Card.DownloadedFields |= Card.Actions.Comments;
```

Do this in your setup/bootstrap. That should get you going.

**Comment by Racoon77** [comment]
Amazing, thanks. Worked like a charm.

And how would I change the limit? Currently, I'm limited to 100.
```card.Comments.Limit(1000)``` as suggested [here](https://stackoverflow.com/questions/41114910/how-to-pass-parameter-like-before-and-limit-in-manatee-trello-methods) is no longer valid, neither is ```Collections.Limit(card.Comments, 1000)```.

Setting the limit via the *int?* property: ```card.Comments.Limit = 1000;``` still returns at most 100 comments.

**Comment by gregsdennis** [comment]
Hm... the property should work.  I'll look into that.

Where did you see the docs seeing the limit via a method? That's old, and I need to update it.

**Comment by gregsdennis** [comment]
@Racoon77 I added a couple tests that demonstrate that the limit property is working.  The first gets 10 of 20 comments (less that the default).  The second gets 70 of 100 comments (more than the default).

https://github.com/gregsdennis/Manatee.Trello/blob/master/Manatee.Trello.IntegrationTests/CardTests.cs#L276-L333

**Comment by Racoon77** [comment]
Thank you. The problem was that I was refreshing the card and it didn't occur to me comments should be refreshed as well.
That Limit example comes from an old [StackOverflow question](https://stackoverflow.com/questions/41114910/how-to-pass-parameter-like-before-and-limit-in-manatee-trello-methods) which I went to because I couldn't find many examples in the [GitHub Pages](https://gregsdennis.github.io/Manatee.Trello/examples/getting-boards.html) documentation. Now I see the tests could serve as examples pretty well, too.

Thanks for your help, now it should be okay.

**Comment by gregsdennis** [comment]
That's odd. I would think the card refresh would download the comments given the set downloaded fields.  I'll run some more experiments.

Glad you got it working, though. Thanks for the links.
