### ISSUE TITLE
PowerUp: Custom Fields - Type: Numbers bug

### ISSUE THREAD

**Issue by MichaelStratigos** [gregsdennis/Manatee.Trello#277]
**Issue:**
The particular powerup gives you the ability of creating custom fields by selecting a name of the field and its type. These is a new Custom Fields button on each card from which you select which fields to show from the ones you have already selected. The bug is with the numeric values of custome field with type Number. Trello allows one to have numbers with decimal point like 0.5 or 9.6. 
Manatee.Trello retrieves this information as a single string of "{Name of field} - {value}". So for example for the field SpentTime of a card with value 9.6 I should get "Spent Time - 9.6" or "Planned Time - 0.5". Instead we are getting "Spent Time - 96" or "Planned Time - 5". 

**To Reproduce:**
1. Add PowerUp for CustomFields
2. Create a numeric CustomField and add it to a card.
3. Give it a decimal point value, e.g. 0.5 or 9.6
4. Retrieve from Manatee.Trello

The code I am using for retrieving the value is to manipulate the string like below (example based to our custom fields names):

```
decimal  plannedTime = 0;
decimal  spentTime = 0;
 if (card.CustomFields.Any(x => x.Definition.Name.ToLower() == "planned time"))
                        decimal.TryParse(
                            card.CustomFields.First(x => x.Definition.Name.ToLower() == "planned time").ToString()
                                .Split('-')[1].Trim(), out plannedTime);
                    if (card.CustomFields.Any(x => x.Definition.Name.ToLower() == "spent time"))
                        decimal.TryParse(
                            card.CustomFields.First(x => x.Definition.Name.ToLower() == "spent time").ToString()
                                .Split('-')[1].Replace(".",",").Trim(), out spentTime);

```

**Expected behavior:**
e.g. for Planned Time entered 0.5 we get 
   plannedTime = 0.5 but instead is 5 (because returned is  "Planned Time - 5")
e.g. for Spent Time entered 9.6 we get 
   spentTime = 9.6 but instead is 96 (because returned is "Spent Time - 96"

----
.Net version : 4.6.2

**Comment by gregsdennis** [comment]
Why are you doing a `.ToString()` on the custom field if you know it's numeric?  You should be able to simply cast it to `NumberField` and get the value that way.

```csharp
var field = card.CustomFields.FirstOrDefault(f =>
    string.Equals(f.Definition.Name, "planned time", StringComparison.InvariantCultureIgnoreCase);
var numericField = field as NumberField;
var value = numberField?.Value;
```

**Comment by gregsdennis** [comment]
I set up the following test which passes:

```csharp
[Test]
public async Task Issue277_NumericCustomFields()
{
    var card = await TestEnvironment.Current.BuildCard();
    await TestEnvironment.Current.Board.EnsurePowerUp(new CustomFieldsPowerUp());

    // create the numeric custom field called "planned time"
    var definition = await TestEnvironment.Current.Board.CustomFields.Add("planned time", CustomFieldType.Number);

    // set the value
    await definition.SetValueForCard(card, 0.5);

    // force a refresh to pull down the value
    await card.CustomFields.Refresh(true);

    // ensure the field is numeric and contains the correct value
    var field = card.CustomFields.First(x => x.Definition.Name.ToLower() == "planned time");
    var numberField = field as NumberField;
    Assert.AreEqual(0.5, numberField?.Value);

    // validate that parsing the field's string output also works
    decimal.TryParse(card.CustomFields.First(x => x.Definition.Name.ToLower() == "planned time").ToString()
                            .Split('-')[1].Trim(), out var plannedTime);
    Assert.AreEqual(0.5m, plannedTime);
}
```

**Comment by MichaelStratigos** [comment]
Hello Greg.

Although I can see your test is working, there is a difference which makes it not matching the real case scenario. This is that you actually set the value of the numeric through code. And yes it works. But if you create a card to a Trello and add a numeric field and set it to a decimal number, then, retrieving it you will get an integer.

Please have a look at the attached screenshots. These are from the actual application stopped to a breakpoint and checking a particular card's values. 

**Screenshot with Trello showing the actual card values,**

![image](https://user-images.githubusercontent.com/25932513/50383782-f24c0080-06c2-11e9-834d-16dca6e36817.png)


**Screenshot with Visual Studio debugger and the card values retrieved by Manatee.Trello.**

![image](https://user-images.githubusercontent.com/25932513/50383785-00018600-06c3-11e9-8ee2-475a2157dd37.png)

Thanks,
M

**Comment by gregsdennis** [comment]
I just set up the following test as you suggested

```
[Test]
public async Task Issue277_SetCustomFieldInBrowser()
{
    var card = TestEnvironment.Current.Factory.Card("KU54lK54");
    await card.Refresh();

    // client way
    decimal.TryParse(card.CustomFields.First(x => x.Definition.Name.ToLower() == "field #1")
        .ToString()
        .Split('-')[1].Trim(), out var fieldValue);

    fieldValue.Should().Be(5.8m);

    // via field
    var field = card.CustomFields.First(x => x.Definition.Name.ToLower() == "field #1") as NumberField;
    field.Value.Should().Be(5.8);
}
```

It reads [this card](https://trello.com/c/KU54lK54/1398-issue-277-numeric-custom-fields-not-recognizing-floating-point-portion-of-value).  Everything was set up through the browser, and I'm just reading the card data in the test.

While those screenshots help, I'd like to see the raw data, please.  Can you capture the API call with fiddler and send the JSON?  (Slack is fine, if you like.)
