### ISSUE TITLE
Json.Serialization exception

### ISSUE THREAD

**Issue by tim-invinciblecat** [gregsdennis/Manatee.Trello#279]
Hi there!

First of thanks the amazing work :)

I just have a weird issue.
The code worked like a charm yesterday and now when I try to do this (please note that I did not change the code at all from yesterday and it was working before)

_me = await _factory.Me();

it throws this exception:
NullReferenceException: Object reference not set to an instance of an object
Manatee.Json.Serialization.Internal.Serializers.NullableSerializer._Decode[T] (Manatee.Json.Serialization.SerializationContext context) (at <ee51fd8653414dabb052b80a25619a0e>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Manatee.Json.Serialization.Internal.Serializers.GenericTypeSerializerBase.Deserialize (Manatee.Json.Serialization.SerializationContext context) (at <ee51fd8653414dabb052b80a25619a0e>:0)
Manatee.Json.Serialization.Internal.Serializers.DefaultValueSerializer.Deserialize (Manatee.Json.Serialization.SerializationContext context) (at <ee51fd8653414dabb052b80a25619a0e>:0)
Manatee.Json.Serialization.Internal.Serializers.SchemaValidator.Deserialize (Manatee.Json.Serialization.SerializationContext context) (at <ee51fd8653414dabb052b80a25619a0e>:0)
Manatee.Json.Serialization.JsonSerializer.Deserialize (Manatee.Json.Serialization.SerializationContext context) (at <ee51fd8653414dabb052b80a25619a0e>:0)
Manatee.Json.Serialization.JsonSerializer.Deserialize (System.Type type, Manatee.Json.JsonValue json) (at <ee51fd8653414dabb052b80a25619a0e>:0)
Manatee.Json.Serialization.JsonSerializer.Deserialize[T] (Manatee.Json.JsonValue json) (at <ee51fd8653414dabb052b80a25619a0e>:0)
Manatee.Trello.Json.Entities.JsonExtensions.Deserialize[T] (Manatee.Json.JsonObject obj, Manatee.Json.Serialization.JsonSerializer serializer, System.String key) (at <a0b6a6ea15e04ad5a94bf37479bb7883>:0)
Manatee.Trello.Json.Entities.ManateeAction.FromJson (Manatee.Json.JsonValue json, Manatee.Json.Serialization.JsonSerializer serializer) (at <a0b6a6ea15e04ad5a94bf37479bb7883>:0)
Manatee.Json.Serialization.Internal.Serializers.JsonSerializableSerializer.Deserialize (Manatee.Json.Serialization.SerializationContext context) (at <ee51fd8653414dabb052b80a25619a0e>:0)
Manatee.Json.Serialization.Internal.Serializers.ReferencingSerializer.Deserialize (Manatee.Json.Serialization.SerializationContext context) (at <ee51fd8653414dabb052b80a25619a0e>:0)
Manatee.Json.Serialization.Internal.Serializers.DefaultValueSerializer.Deserialize (Manatee.Json.Serialization.SerializationContext context) (at <ee51fd8653414dabb052b80a25619a0e>:0)
Manatee.Json.Serialization.Internal.Serializers.SchemaValidator.Deserialize (Manatee.Json.Serialization.SerializationContext context) (at <ee51fd8653414dabb052b80a25619a0e>:0)
Manatee.Json.Serialization.JsonSerializer.Deserialize (Manatee.Json.Serialization.SerializationContext context) (at <ee51fd8653414dabb052b80a25619a0e>:0)
Manatee.Json.Serialization.Internal.Serializers.ListSerializer._Decode[T] (Manatee.Json.Serialization.SerializationContext context) (at <ee51fd8653414dabb052b80a25619a0e>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
Manatee.Trello.Internal.DataAccess.JsonRepository.ValidateResponse (Manatee.Trello.Rest.IRestResponse response) (at <a0b6a6ea15e04ad5a94bf37479bb7883>:0)
Manatee.Trello.Internal.DataAccess.JsonRepository+<ProcessRequest>d__7`1[T].MoveNext () (at <a0b6a6ea15e04ad5a94bf37479bb7883>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Manatee.Trello.Internal.DataAccess.JsonRepository+<Execute>d__1`1[T].MoveNext () (at <a0b6a6ea15e04ad5a94bf37479bb7883>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Manatee.Trello.Internal.Synchronization.SynchronizationContext`1+<GetData>d__16[TJson].MoveNext () (at <a0b6a6ea15e04ad5a94bf37479bb7883>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Manatee.Trello.Internal.Synchronization.DeletableSynchronizationContext`1+<GetData>d__7[T].MoveNext () (at <a0b6a6ea15e04ad5a94bf37479bb7883>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Manatee.Trello.Internal.Synchronization.SynchronizationContext`1+<GetBasicData>d__20[TJson].MoveNext () (at <a0b6a6ea15e04ad5a94bf37479bb7883>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Manatee.Trello.Internal.Synchronization.SynchronizationContext+<Synchronize>d__21.MoveNext () (at <a0b6a6ea15e04ad5a94bf37479bb7883>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
KittenEngine.Trello.KnTrello+<AddCardAsync>d__2.MoveNext () (at Assets/Trello/KnTrello.cs:34)
UnityEngine.Debug:LogException(Exception)
KittenEngine.Trello.<AddCardAsync>d__2:MoveNext() (at Assets/Trello/KnTrello.cs:49)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:SetException(Exception)
Manatee.Trello.Internal.Synchronization.<Synchronize>d__21:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
Manatee.Trello.Internal.Synchronization.<GetBasicData>d__20:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
Manatee.Trello.Internal.Synchronization.<GetData>d__7:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
Manatee.Trello.Internal.Synchronization.<GetData>d__16:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
Manatee.Trello.Internal.DataAccess.<Execute>d__1`1:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
Manatee.Trello.Internal.DataAccess.<ProcessRequest>d__7`1:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(IRestResponse)
Manatee.Trello.Internal.RequestProcessing.<Process>d__9:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(IRestResponse)
Manatee.Trello.Internal.RequestProcessing.<Execute>d__10:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(IRestResponse)
Manatee.Trello.Internal.RequestProcessing.<<AddRequest>b__0>d:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(IRestResponse`1)
Manatee.Trello.Rest.<ExecuteAsync>d__9`1:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(IRestResponse`1)
Manatee.Trello.Rest.<ExecuteWithRetry>d__12`1:MoveNext()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by gregsdennis** [comment]
Thanks for the report.  That *is* a strange error.  I'll investigate and let you know.

**Comment by tim-invinciblecat** [comment]
Thanks a lot.
Here is the code in case:

```
public static void Init(string pAppKey, string pToken)
        {
            TrelloAuthorization.Default.AppKey = pAppKey;
            TrelloAuthorization.Default.UserToken = pToken;
        }

public static async Task<bool> AddCardAsync(string pBoardId, string pName, string pDescription, params (string name, byte[] content)[] pAttachements)
        {
            try
            {
                if (_factory == null)
                {
                    _factory = new TrelloFactory();
                }
                if (_me == null)
                {
                    _me = await _factory.Me();
                }

                IBoard board = _factory.Board(pBoardId);
                await board.Refresh();
                ICard card = await board.Lists[0].Cards.Add(pName, description: pDescription);

                foreach (var iAttachement in pAttachements)
                {
                    await card.Attachments.Add(iAttachement.content, iAttachement.name);
                }

                await card.Refresh();

                return true;
            }
            catch (Exception exception)
            {
                UnityEngine.Debug.LogException(exception);
                return false;
            }
        }
```

**Comment by tim-invinciblecat** [comment]
Also for what I understand, it seems to come from line 70 of SynchronizationContext:
object basicData = await this.GetBasicData(ct);

**Comment by tim-invinciblecat** [comment]
Hey!
I just tried something. So... I changed the API key and User Token using another account and... it seems to work. Any idea why? Could the account or the app key be banned or something?

**Comment by tim-invinciblecat** [comment]
Is the API storing any files? Could their be a file that hasn't been serialized properly or something? Maybe a key in the registry?

I will try.
Quick question to make sure I am doing things right.
So basically, the idea is to allow my users (in my game) to report bugs / glitches.
To do so, they would create a card in my Trello board with an attached png / jpg.

Is there a way to do so without having all my users needed their own Trello account?
So far I though about using my own app_key and user_token but is the user_token expiring?
If this is a bad idea how would you do it?

(Also, I couldn't find how to generate user token from the API, could you help me out?)

Thanks,
-Tim

**Comment by tim-invinciblecat** [comment]
(Sorry for spamming)
Interesting thing... It seems that it is also related to the board.
I created a new user and granted him access to the same board, it did not work. When I changed the board, it worked. Is there anything that is stored? Or could Trello block anything if they think there is a suspicious activity?

**Comment by gregsdennis** [comment]
There may be something weird stored.  I had one case where my serializer wasn't handling international characters correctly.  If you can grant me temporary access, I can test it.  Otherwise, I'll need the data from it; you can capture that with Fiddler.

Regarding having your users create Trello accounts, I would suggest maybe you implement [emailed cards](https://help.trello.com/article/809-creating-cards-by-email).  They wouldn't need to create a Trello account, and you might not even need to interface directly with Trello from your app/game; you just send an email.

**Comment by tim-invinciblecat** [comment]
Thank you so much. I will use emailed cards. Even if I would have like to be able to set also custom fields, it seems like the best option so far!

**Comment by gregsdennis** [comment]
If you have any more trouble, please feel free to hit me up on slack.  It may be a better forum for a conversation than a GH issue.
