### ISSUE TITLE
Exception when reading custom fields definition when the board have a deleted custom field

### ISSUE THREAD

**Issue by FernandoBarbieri** [gregsdennis/Manatee.Trello#280]
Hello, thank you for this library, it is helping me a lot integrating trello with my application.

I have this problem:

If one of the custom fields of a board is deleted in Trello, an exception is trown when I try to run board.Cards.Refresh();

**To Reproduce**
[In Trello]
1. Create a new Trello board
2. Add a custom field
3. Remove the custom field

[In the application]
```
var board = new Board(boardId);
await board.Cards.Refresh();
```

When I call board.Cards.Refresh(), a System.Reflection.TargetInvocationException with a NullReferenceException inner exception is trown.

The exception happens in the class JsonExtensions when it tries to deserialize the deleted custom field.

```
if (!obj.ContainsKey(key)) return default(T);
return serializer.Deserialize<T>(obj[key]); // <- here
```

Thanks.

**Comment by gregsdennis** [comment]
Thanks for reporting this, and for narrowing down the circumstances.  I'll build a test around this and investigate.

**Comment by gregsdennis** [comment]
Looks like this and #281 are the same issue.  Since that one deals with the missing action type more directly, I'm going to track it on that one.
