### ISSUE TITLE
Bulk Refresh All Custom Fields of all Cards not working.

### ISSUE THREAD

**Issue by sannip** [gregsdennis/Manatee.Trello#284]
Based on this [/issues/252]([https://github.com/gregsdennis/Manatee.Trello/issues/252]) I should be able to get all custom fields of cards using the below code.

`					var board = _factory.Board(TrelloIds.BoardId);`
					`await board.Refresh(ct: ct);`
					`await board.Cards.Refresh(ct: ct);`
					`Console.WriteLine(board.Cards[0].CustomFields[0].Definition.Name);`

But CustomFields do not return any data.

**Comment by gregsdennis** [comment]
I swear this was working.  Now Trello's not returning custom field data.  I'll have to verify the API docs and check with them.

**Comment by gregsdennis** [comment]
Doesn't look like the API's changed.  I've posted a question on their Slack workspace.

**Comment by gregsdennis** [comment]
Okay... so the issue is context.  I need to use `cards_customFieldItems` when requesting a board and I want the cards included, but use `customFieldItems` when a card is the primary object type.

I'll have to work this out.

**Comment by gregsdennis** [comment]
@sannip please give v3.6.1 a try.  You also won't need that second refresh.  Just refreshing the board should give you the data you need.

**Comment by gregsdennis** [comment]
Please hold.  I'm having trouble with MyGet...

**Comment by gregsdennis** [comment]
Okay. v3.6.1 has been pushed.

**Comment by sannip** [comment]
Bulk Refresh is working fine now.

Thanks

**Comment by gregsdennis** [comment]
Thanks for the confirmation
