### ISSUE TITLE
System.InvalidOperationException: Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by dedady157** [gregsdennis/Manatee.Trello#289]
**Describe the bug**
it thrown an exception about updating a collection while its in a readonly state, IE foreach. this didn't happen on my Win7 machine it just started once i moved to the linux server.

**To Reproduce**
```C#
public static async Task INIT()
{
    TrelloAuthorization.Default.AppKey = API_INFO.APIKEY;
    TrelloAuthorization.Default.UserToken = API_INFO.TOKEN;
    ExhibitionDiscordBot= new Board(API_INFO.EDB_BOARDID);
    MBRP = new Board(API_INFO.MBRP_BOARDID);
    DRP = new Board(API_INFO.DRP_BOARDID);
    PRP = new Board(API_INFO.PRP_BOARDID);
    Rust = new Board(API_INFO.RUST_BOARDID);
    try
     {
        Task.WaitAll(
            ExhibitionDiscordBot.Refresh(true),
            MBRP.Refresh(true),
            DRP.Refresh(true),
            PRP.Refresh(true),
            Rust.Refresh(true)
        );
    }
    catch(Exception E) { Logging.Log(new LogMessage(LogSeverity.Error, "Trello", "Exception was thrown while waitting on board updates", E)); }
}
```

**Expected behavior**
it shouldn't throw an exception at all

**Screenshots**
https://pastebin.com/5pKXpWWB

**Desktop (please complete the following information):**
 - OS: Debain Server (18.04.2 LTS (Bionic Beaver))
- .Net Core 2.2
 - Version 3.6.1

**Additional context**
this works on Win7 .Net Core 2.2
its running in a deamon, it was recompiled on the machine before executing it.
all the board id's are corrent same as the APIKey and Token

**Comment by gregsdennis** [comment]
Thanks for the report (and a nice one at that)!  Can you give me a stack trace? I'd like to find out where the exception was thrown.

**Comment by dedady157** [comment]
look at the pastebin, thats the full exception dump
the function that threw it is: Manatee.Trello.Internal.DataAccess.JsonRepository.ValidateResponse(IRestResponse response)

**Comment by dedady157** [comment]
its an issue with multithreading, running the refreshes after one and other, works without issue

**Comment by dedady157** [comment]
Code:
```C#
Console.WriteLine("0");
ExhibitionDiscordBot.Refresh(true).Wait();
Console.WriteLine("1");
MBRP.Refresh(true).Wait();
Console.WriteLine("2");
DRP.Refresh(true).Wait();
Console.WriteLine("3");
PRP.Refresh(true).Wait();
Console.WriteLine("4");
Rust.Refresh(true).Wait();
```
Console:
```
Mar 01 04:44:51 server exhibitionbot-service[13025]: 0
Mar 01 04:44:54 server exhibitionbot-service[13025]: 1
Mar 01 04:44:54 server exhibitionbot-service[13025]: 2
Mar 01 04:44:55 server exhibitionbot-service[13025]: 3
Mar 01 04:44:56 server exhibitionbot-service[13025]: 4
```

**Comment by gregsdennis** [comment]
I don't really have enough info from that stack trace in the pastebin. Could you check if there is an inner exception, please?

**Comment by dedady157** [comment]
cant help you there, its on a remote linux machine, and i cant bring the bot down for long. so sorry man
