### ISSUE TITLE
Card.CustomFields.Definition.Name is not set for some of the custom fields.

### ISSUE THREAD

**Issue by sannip** [gregsdennis/Manatee.Trello#292]
Custom Fields Definition.Name is null for some of the custom fields. I ran the unit test "TestMethod1" from Manatee.Trello.UnitTests and observed that there are five custom fields and Definition.Name is set for only one of them. 

![image](https://user-images.githubusercontent.com/35477445/54321440-4244be80-4645-11e9-95bc-5762f2bdb660.png)

**Comment by gregsdennis** [comment]
Thanks for reporting this.  I'll look into it.

**Comment by gregsdennis** [comment]
I set up some tests.  Looks like this definitely an issue.  I'll have to dig deeper.

**Comment by gregsdennis** [comment]
I think this was incorrectly closed.

**Comment by gregsdennis** [comment]
I verified that the `name` property is turned by the API. It seems there is a break in the data flow at either serialization or in the context layer.

**Comment by gregsdennis** [comment]
I got it.  It's the action data (and probably notification data, too).  It's attempting to use cached items, but it shouldn't because these should be snapshots of items.  It's only doing this for custom fields.

Now that I know what the problem is, I can fix it!

**Comment by gregsdennis** [comment]
See Manatee.Trello v3.8.1
