### ISSUE TITLE
CustomFields pulling Null?

### ISSUE THREAD

**Issue by sdudley7** [gregsdennis/Manatee.Trello#297]
**Describe the bug**
Both CustomFields methods return null on a Card level and Board level.

**To Reproduce**
Test code

      var cards = board.Cards;

                Console.WriteLine(cards.Count());

                foreach (var card in board.Cards)
                {
                    Console.WriteLine(card.ToString());
                    Console.WriteLine(card.CustomFields.Count());
                    foreach (var field in card.CustomFields)
                    {
                        Console.WriteLine(field);
                        Console.WriteLine(field.ToString());
                        Console.WriteLine(field.Definition);
                    }
                        Console.WriteLine(card.ToString());
                }

**Expected behavior**
Should return the custom fields per card

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
- .Net 4.5

**Additional context**

**Comment by gregsdennis** [comment]
Thanks for reporting this.

I don't see any refresh calls in there.  Are you not calling `.Refresh()`, or did you just omit them for the report?

**Comment by sdudley7** [comment]
Thank you Greg, I refresh the lists and cards before requesting the fields.

                await board.Lists.Refresh();
                await board.Cards.Refresh();

**Comment by sdudley7** [comment]
This can be closed. Was testing on the wrong board! Sorry and thank you!
