### ISSUE TITLE
Create a card with a member attached

### ISSUE THREAD

**Issue by MaxDuggan** [gregsdennis/Manatee.Trello#301]
Hi, I'm not sure if there is something I'm missing but I am having trouble with creating a card and having a member associated with it on creation. I am trying to create cards from an existing source with the task, due date, and member associated with them and adding those cards to a list. Other than the member part this package is working great and easy to understand. 

I'm using: list.Cards.Add(taskName, null, null, dueDate, false, List<Member>, null); 
(Members created based on Trello username)
Should I be using a different type for the members associated? Alternatively, is there a way to add a member to a card by username if you have the card ID? This alternative would make the process much easier for me.

Thanks in advance for the help and also for creating this awesome package!

**Comment by gregsdennis** [comment]
You should be able to add members via that call. (I'm not sure what `List` is in your example.  That's the `members` parameter.)  You'll need to download a member object to pass into it, though:

```c#
var member = factory.Member("username"); // you can fetch the member by username,
await member.Refresh(); // but to add them to the card, you need the ID; refresh to get it.

// If you're only using a few of the parameters, I suggest naming your parameters and leaving
// out the others.  They'll use nulls when not specified.
// Only "name" is required for this call.
list.Cards.Add(name: "card name", dueDate: dueDate, members: new[] {member});
```

If that's not working, please let me know.

**Comment by MaxDuggan** [comment]
I was creating new member objects rather than fetching existing members. Your way works like a charm, thanks for the help!
