### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by lijunle** [gregsdennis/Manatee.Trello#306]
**Describe the bug**

It is hard to describe or repro the bug. I rerun this Trello in an Azure function every 5 minutes. From the telemetry, it spend longer and longer time to send the requests. My guess is, there is some memory leak issue in the code. Do you have any ideas?

**Screenshots**

Vertical axis is the time to send the request.

![image](https://user-images.githubusercontent.com/1296500/64375544-f9aa0480-cfda-11e9-9dbb-8e985fbfcd42.png)

**Desktop (please complete the following information):**
 - OS: Linux
- .Net Target: .Net core 2.2

**Additional context**

I tried to call `TrelloConfiguration.Cache.Clear()` after each call but it does not help.

**Comment by gregsdennis** [comment]
Thanks for reporting this.  Do you modify `TrelloConfiguration` at all, or are you using the default settings.

Also, can you let me know what package version you're using, please?

**Comment by lijunle** [comment]
No modification on `TrelloConfiguration` class.

Version 3.8.1.

**Comment by lijunle** [comment]
The source code is here: https://gist.github.com/lijunle/eafa8cb87f651b2dd904c8352ed5e6c6

It is quite short.

**Comment by gregsdennis** [comment]
Thanks. I'll have a look tonight.

**Comment by gregsdennis** [comment]
So it looks like there _may_ be a memory leak, but I don't think that's the primary issue.  The `EventAggregator` holds on to everything that subscribes using weak references until it discovers (through an event publish) that it doesn't exist.

However, with each subscriber, it must check to see if that object hasn't already subscribed, and just about _every_ object subscribes.  As the number of subscribers increases, this check takes more and more time.  This is the source of the increasing delay.

I'll be publishing v3.10.1 soon, which completely disables the `EventAggregator` when consistency processing is disabled (which appears to be your case).

**Comment by lijunle** [comment]
@gdziadkiewicz From monitor, the issue is resolved! Thanks a lot for the quick help!

**Comment by lijunle** [comment]
Hmm... The request time is stable, however, there is still some kinds of memory leak.

![image](https://user-images.githubusercontent.com/1296500/64640068-1a4cd280-d3be-11e9-99ab-0b5c3f2aeb43.png)

**Comment by lijunle** [comment]
![image](https://user-images.githubusercontent.com/1296500/65199115-69d47380-da3a-11e9-9986-974ab9c9a4f7.png)

It shows the `BoardContext` is never released. I took a quick look at the code. This line of code is strange. The `Synchronized` handler is never released.

https://github.com/gregsdennis/Manatee.Trello/blob/1b40470dfb1c9b6abe79b740a2a601cec37d885f/Manatee.Trello/Board.cs#L379

**Comment by lijunle** [comment]
@gregsdennis Why the `Synchronized` is declared as an `event`? It sounds should be a weak reference callback on the constructor.

https://github.com/gregsdennis/Manatee.Trello/blob/cce81cbab2688f4f7a1a2a6a47f5b408d81f4f75/Manatee.Trello/Internal/Synchronization/SynchronizationContext.cs#L26
