### ISSUE TITLE
Memory leak on the context classes

### ISSUE THREAD

**Issue by lijunle** [gregsdennis/Manatee.Trello#308]
**Describe the bug**

After a long run on my service, the memory grows a lot. After analyze the memory dump, there are lots of context classes not released.

![image](https://user-images.githubusercontent.com/1296500/65199115-69d47380-da3a-11e9-9986-974ab9c9a4f7.png)

**Desktop (please complete the following information):**
 - OS: Windows
- .Net Target; .Net Core 2.2 
 - Version: v3.10.1

**Additional context**

This is a follow up on #306 

I checked the code. It shows the `BoardContext` is never released. I took a quick look at the code. This line of code is strange. The `Synchronized` handler is never released.

https://github.com/gregsdennis/Manatee.Trello/blob/1b40470dfb1c9b6abe79b740a2a601cec37d885f/Manatee.Trello/Board.cs#L379

This seems a general issue on all context classes.

https://github.com/gregsdennis/Manatee.Trello/blob/ad33fa0a6bac4ad9fc629634ca39fdd3175bf3c7/Manatee.Trello/Card.cs#L429

**Comment by gregsdennis** [comment]
From https://github.com/gregsdennis/Manatee.Trello/issues/306#issuecomment-532918784
> It sounds should be a weak reference callback on the constructor.

I'll look into this idea.

**Comment by mrsalmon1976** [comment]
I'm experiencing this too.  I have a Windows service running that updates board information, and after a day or so it starts suffering OutOfMemoryExceptions when calling Refresh on a board retrieved from the factory.
