### ISSUE TITLE
Board API invalid value for plugins

### ISSUE THREAD

**Issue by vupham84** [gregsdennis/Manatee.Trello#310]
Hi all,

Not sure what Trello API has updated but it breaks the Manatee Trello. I'm getting Board as below.

 var board = new Board(boardID);
 await board.Refresh();

It was working fine but suddenly stops working today. I get the error "API invalid value for plugins".

After looking at the code, I see Manatee generates the parameters like this in BoardContext.cs

if (parameterFields.HasFlag(Board.Fields.PowerUps)) Parameters["plugins"] = "true";

If we remove that "plugins" parameter from Parameters, we won't get error anymore. It looks like Trello API doesn't accept the parameter plugins anymore.

However, I don't know how to remove or override that code in my code base. Please help.

**Comment by Kreepounet** [comment]
Same problem here

**Comment by gregsdennis** [comment]
Yeah, I've received several other reports of this.

Please follow this issue I've filed in their community: https://community.developer.atlassian.com/t/custom-fields-in-the-api-broken/32133?u=gregsdennis

**Comment by Kreepounet** [comment]
I don't have any power-up activated on the board that returns this error so it doesn't seem to come from Custom Fields.

**Comment by gregsdennis** [comment]
Good insight, @Kreepounet.  I'll look into that.

**Comment by Alex-Grz** [comment]
Experienced same problem with this code::
       CurrentBoard = factory.Board(MyBoardShortId);
       await CurrentBoard.Refresh();   -> error "API invalid value for plugins"

I have 1 power-up on my board : calendar
The problem disappeared with :
       Board.DownloadedFields &= ~Board.Fields.PowerUps;

This is ok for me because I don't need to retrieve power-ups.

**Comment by Kreepounet** [comment]
@Alex-Grz : This fix works for me, thanks a lot.

**Comment by gregsdennis** [comment]
@Alex-Grz thanks for posting the code for the workaround.

**Comment by gregsdennis** [comment]
They are now validating the `plugins` parameter when requesting a board.  I'll have to ship an update to fix everyone.

**Comment by gregsdennis** [comment]
I'll be publishing v3.10.2 which should fix this.  Thanks for the reports, everyone.
