### ISSUE TITLE
LicenseHelpers fails to parse DateTime

### ISSUE THREAD

**Issue by sveinpg** [gregsdennis/Manatee.Trello#311]
**Describe the bug**
`Manatee.Trello.Internal.Licensing.LicenseHelpers` throws an `System.TypeInitializationException`.

I suspect that this is because of my prefered language in windows (Norwegian)

```
System.TypeInitializationException: The type initializer for 'Manatee.Trello.Internal.Licensing.LicenseHelpers' threw an exception.
 ---> System.FormatException: String '2019-10-07T14.11.17.610Z' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
```

**To reproduce**
Set environment variable `TRELLO_LICENSE_TRACKING: {"Submissions":1,"SessionExpiry":"2019-10-07T14.11.17.610Z"}`

This is snippet that fails: 
```
const string feedbackBoardId = "Some random ID";
var board = _trelloFactory.Board(feedbackBoardId, TrelloAuthorization.Default);
await board.Refresh();`
```

**Expected behavior**
Expected the helper to read the string as a valid date. 

**Desktop**
 - OS: Windows
- .Net Target: Std2.0 (.net core 3.0)
 - Version: 3.10.2

**Comment by gregsdennis** [comment]
LicenseHelpers has no special logic to format the date.  It just uses a JSON deserializer (from Manatee.Json).  That's set up to use ISO8601 date formatting.

`2019-10-07T14.11.17.610Z` isn't ISO8601-formatted.  You need colons `:` instead of dots `.` between the year/month/day values.

The only reason this could be formatted incorrectly is that it's being set manually.  Please don't edit this value.

**Comment by sveinpg** [comment]
I did not edit or set the value manually. So apparantly that is not the only reason why it could be formatted incorrectly.

**Comment by gregsdennis** [comment]
Okay. I'll explore some more. I haven't had time to look into it yet.

**Comment by gregsdennis** [comment]
Please see v3.10.3.  I've removed the license requirement (something that I've been contemplating for a while).  Thanks for using my library.
