### ISSUE TITLE
Allow passing auth info to "Me()"

### ISSUE THREAD

**Issue by nimrodolev** [gregsdennis/Manatee.Trello#313]
**Does Trello do something you can't automate with this library?  Can this library make doing something simpler?**
The `ITrelloFactory.Me()` method does not currently support passing in an instance of `TrelloAuthorization`, and instead reads the values from the static `TrelloAuthorization.Default`. It would be great if that limitation is removed by adding another overload that supports this argument.

**Describe alternatives you've considered**
It's possible to re-assign the static `TrelloAuthorization.Default` every time you need to perform a call for a different user. However, on a multi-threaded server handling requests for multiple users, this kind of solution will be either very dangerous (allowing for concurrency races) or very slow (if we were to, for example, lock every call to make sure settings are always correct).

**Additional context**
It seems like all other methods support this, which makes a lot of sense when you consider applications that serve many different users and manage a big set of user tokens. I think adding support for custom auth for `Me()` calls is more a standardization, making it more compatible with the rest of the library's API, than an actual feature.

**Comment by gregsdennis** [comment]
> which makes a lot of sense when you consider applications that serve many different users

I hadn't considered this use case. The reason I supported different authorization for the other object was for syncing data across entities that different users had access to.  User-based actions is a good use case for multiple `Me` objects.

**Comment by nimrodolev** [comment]
@gregsdennis does that mean you'd want to adopt such an addition? Are you open to a PR for this?

**Comment by gregsdennis** [comment]
I am open to that.  Tried to work on it a bit earlier today.  I'm having issues building a multi-targeted project since I updated VS.

**Comment by gregsdennis** [comment]
I got the lib running again, but I had to drop multi-targeting.  It only builds to `.netstandard2.0` now, but that's acceptable.  I'll have to do a major version bump if I can't get the multi-targeting working again.

**Comment by gregsdennis** [comment]
I've created a new branch: [release/4.0.0](https://github.com/gregsdennis/Manatee.Trello/tree/release/4.0.0).  If you create a PR, please pull into that branch instead of master.

**Comment by nimrodolev** [comment]
Hey, issued a PR for this - I may be missing something but it was a pretty straightforward change. 
I didn't understand how to run the integration tests, but all of the unit tests are passing, and AppVeyor build failed but that seems to be completely unrelated to the actual changes. 

I tried to get rid of all the formatting changes the VS did, sorry for the ones that were left 😬 Either way should be hard to go over the changes - they're pretty minor.

**Comment by gregsdennis** [comment]
Thanks. Saw it.  I left a couple remarks.
