### ISSUE TITLE
Board.Actions will only return 50 Items

### ISSUE THREAD

**Issue by davestuart** [gregsdennis/Manatee.Trello#317]
Hi, I only started using Manatee.Trello yesterday and figured out how to get it working for the most part. Never dealt with Async stuff before so that was new. Anyway, I want to get ALL Actions from a Board but not matter what I do it will only return 50 when I know there is a lot more. I don't know what I'm doing wrong.

This is a .NET Forms App with C#. I'm using private form level declarations to make it easy. I'm not using the Return on the Sync calls at all.

The other weird thing is that I have to call this twice in order to get the data. First when the form opens and then second when I call the same thing from a Button on the form.

`        
        private TrelloAuthorization _trelloAuthorization;
        private TrelloFactory _factory;
        private Board _board;

        public async Task<Board>  GetBoard()
        {
            _factory = new TrelloFactory();
            var board = _factory.Board("5d6eae8fd0ad2b7111f9120a", _trelloAuthorization);

            _board = (Board)board;
            _board.Actions.Limit = 10000;
            _board.Actions.Filter(System.DateTime.Now, System.DateTime.Now.AddYears(-1));
            await _board.Refresh();

            return (Board)_board;
        }`

I expected to get all the Actions back from the Board, not just 50. Please help. Thanks!

 - OS: Windows 10 Pro
- .Net Target 4.7.2
 - Version 4.0.0

**Comment by gregsdennis** [comment]
Hi @davestuart!  Thanks for the question.

The 50 item limit is actually imposed by the Trello API.  I do have a `.Limit` property on all collections that you can use to override this, but they do have a ceiling for how high it can go (1000).

**Comment by davestuart** [comment]
Hi, thanks for the super fast reply! Can you let me know how I can get around the API limit? Do I maybe have to iterate using the Last Date of the returned 50 to get another 50 with the Filter(Start, End)? Then for each of these I have to call the Refresh?

**Comment by gregsdennis** [comment]
I'll set up a test tonight to ensure that the filter method is working as expected.

Regarding the count, as I mentioned before, you can modify the `.Limit` property.

**Comment by gregsdennis** [comment]
I found that I already have tests for the limit.  I've added one for filtering on dates.  Everything seems to work as expected.

Looking at your code, this line is concerning:

```c#
_board.Actions.Filter(DateTime.Today.AddDays(-30), DateTime.Today.AddYears(-1));
```

The parameters are `start` and `end` in that order, so you're looking from -30d to -1y.  Your start is after your end.  I don't know what Trello does with that.  Maybe ignores it???

**Comment by davestuart** [comment]
Hi, thanks again for the reply. Even just using "_board.Actions.Limit = 1000;" returns 50. As for the dates, even if I switch them around it still does nothing, or even "_board.Actions.Filter(DateTime.Today.AddDays(-1), DateTime.Today.AddDays(-1));" makes no difference. I still cannot control Limit or Filter. I can send you my Visual Studio Solution if you'd like to take a look at it. It's a very simple demo. Can I e-mail that to you?

**Comment by gregsdennis** [comment]
Yeah, I can take a look.

```_board.Actions.Filter(DateTime.Today.AddDays(-1), DateTime.Today.AddDays(-1));```

won't do anything since you're looking at a zero-length time span.

**Comment by davestuart** [comment]
Greg,

 

I sent a OneDrive link to Manatee.Trello@noreply.github.com <mailto:Manatee.Trello@noreply.github.com> . Will you get that or should I use a different e-mail address?

 

Best Regards,
Dave Stuart MCPD
Microsoft Certified Professional Developer
 <http://www.dafran.ca/> Dafran Inc.
403 606-2345
 <mailto:dave.stuart@dafran.ca> dave.stuart@dafran.ca

 <http://www.dafran.ca/>

**Comment by davestuart** [comment]
Hi Greg, let me know how I can send you my Project. I can e-mail you a OneDrive link but do not want to post it here.

**Comment by gregsdennis** [comment]
You can email me at my username here @ Yahoo.

**Comment by gregsdennis** [comment]
It looks like the limit and fields aren't respected when getting the actions as part of the `board.Refresh()` call.  My suggestion is to remove actions from the `Board.DownloadedFields` static property.  This will mean that you'll need to refresh the actions separately, but at the actions collection will need to be refreshed independently.

I have this working and you should get 587 actions.

**Comment by gregsdennis** [comment]
I also found that Trello is returning `memberCreator` (which I'm not deserializing) instead of `idMemberCreator` (which I *am* deserializing) so you get a NRE when trying to print the full name.  I'll need to post an update to fix this.

**Comment by davestuart** [comment]
Thanks Greg. **_board.Actions.Limit = 1000;** followed by **await _board.Actions.Refresh();** worked! But like you said **action.Creator.FullName** is producing a NullReferenceException (NRE). So you are going to fix this and release a new version?

I'm also a bit confused about the **Board.DownloadedFields** static property you mentioned, can you explain what you mean?

**Comment by gregsdennis** [comment]
v4.1.1 is out which should fix the NRE.  Just update the Nuget package and you should be good.

**Comment by davestuart** [comment]
That's perfect Greg! I just got v4.1.1 and the FullName is coming through now, plus I have all 621 Actions now. I understand about the **DownloadedFields** property so thanks for pointing that out.
