### ISSUE TITLE
Auth info not propagating correctly when using new "Me()" method

### ISSUE THREAD

**Issue by nimrodolev** [gregsdennis/Manatee.Trello#323]
**Describe the bug**
When calling `TrelloFactory.Me` and passing in auth info explicitly (i.e. not using the static `TrelloAuthorization.Default`), the auth info is not correctly propagated down to other objects, such as boards. This results in the sub-entities not being correctly fetched from the API.

**To Reproduce**
1. Create an instance of `TrelloFactory`
2. Call `Me(authInfo)`, passing a valid set of Trello credentials as a parameters
3. Inspect the returned `IMe` instance to and see that it's `Boards` collection is empty
4. Call `await me.Boards.Refresh(true)` just to double-check - still empty

**Expected behavior**
The auth info should be used for all `Me`'s sub-entities.

**Comment by gregsdennis** [comment]
Thanks for reporting this. I'll have a look.

**Comment by gregsdennis** [comment]
Your change in included in v3.2.1.  Thank you.
