### ISSUE TITLE
Can't Access the Board Actions until after WinForm is loaded

### ISSUE THREAD

**Issue by davestuart** [gregsdennis/Manatee.Trello#326]
I have a Windows Form in C#. I make the connection, set the Factory, refresh the Board.List and Board.Actions on the initialization of the Form. I have code that then iterates the Board.Actions so that I can output to the Form. The problem I have is that I can't seem to access the Actions until AFTER the Form has Initialized. I have a button that calls the code that will iterate the Actions and that works fine. I can call the same code in a time every 5 seconds and that also works. 

I have tried the same thing in a .NET Console App and since there is no initial event for that type of app I can't get to the "loaded" Actions at all. My goal is to run the code in a .NET Console App so that I have create a WebJob in Azure and have it run on a timer.

It just seems like the board is blank until after the Form has loaded. I was hoping that you could please explain what I'm doing wrong. Thanks!

**Comment by gregsdennis** [comment]
Thanks for the question @davestuart.  Can you provide a snippet of the initialization code you're using?

**Comment by davestuart** [comment]
Thanks! This is the code from the Form.

`   public partial class StartTrello : Form
    {
        private TrelloAuthorization _trelloAuthorization;
        private TrelloFactory _factory;
        private Board _board;
        
        public StartTrello()
        {
            InitializeComponent();

            StartUp();
        }

        private void StartUp()
        {

            // Log in when the Form Opens.
            var apiKey = "apiKey";
            var apiToken = "apiToken";
            MakeTrelloConnection(apiKey, apiToken);

            _factory = new TrelloFactory();
            var board = GetBoard();
            var actions = GetActions();

            TrelloTrawl();
        }

        private void btnTestTrello_Click(object sender, EventArgs e)
        {
            TrelloTrawl();
        }

        public void TrelloTrawl()
        {

            StringBuilder data = new StringBuilder();

            // Examples here: https://github.com/dillenmeister/Trello.NET/wiki/Examples
            // and here: https://csharp.hotexamples.com/examples/TrelloNet/Trello/-/php-trello-class-examples.html

            var counter = 1;
            var actionDescription = "";
            foreach (var action in _board.Actions)
            {
                data.AppendLine("Number: " + counter.ToString());
                // Greg is going to fix the Null Reference Exception for this! 2019-12-14
                data.AppendLine("Full Name: " + action.Creator.FullName);
                data.AppendLine("Action: " + action.ToString());
                data.AppendLine("Date: " + action.Date);

                // There is always an Action Type
                if (action.Type != null)
                {
                    data.AppendLine("Action Type: " + action.Type.Value);

                    switch (action.Type.Value.ToString())
                    {
                        case "updateCard":
                            actionDescription = "";
                            break;

                    }

                    if (actionDescription.Length > 0)
                    {
                        data.AppendLine(actionDescription);
                    }
                }

                if (action.Data.Card != null)
                {
                    data.AppendLine("Card: " + action.Data.Card.Name);
                }

                if (action.Data.ListBefore != null)
                {
                    data.AppendLine("List Before: " + action.Data.ListBefore);
                }

                if (action.Data.ListAfter != null)
                {
                    data.AppendLine("List After: " + action.Data.ListAfter);
                }

                data.AppendLine("");

                counter += 1;
            }

            txtData.Text = data.ToString();
            txtData.Refresh();

        }

        public void MakeTrelloConnection(string key, string token)
        {
            _trelloAuthorization = new TrelloAuthorization();
            _trelloAuthorization.AppKey = key;
            _trelloAuthorization.UserToken = token;
            
        }

        public async Task  GetBoard()
        {
            _factory = new TrelloFactory();
            var board = _factory.Board("[BoardID]", _trelloAuthorization);

            _board = (Board)board;
            await _board.Lists.Refresh();

        }

        public async Task GetActions()
        {
            _board.Actions.Limit = 1000;
            await _board.Actions.Refresh();

        }

        private void timer1_Tick(object sender, EventArgs e)
        {
            TrelloTrawl();
        }
    }
}`

**Comment by davestuart** [comment]
The TrelloTrawl has a blank Board with no Actions. They will only show up when I run it on a timer or click the button.

**Comment by gregsdennis** [comment]
Your `GetBoard()` and `GetActions()` methods are async, returning `Task`s.  Odds are the tasks haven't completed by the time you need the data, so the collections will still be empty.  You'll need to await these tasks.

A **quick-n-dirty hack** solution would be to add `.Result` or `.Wait()` after the method calls, but this isn't really advised.  I suggest looking up how to do async/await in Windows Forms apps.  Ideally you want the processing stuff on another thread so that the UI remains responsive.

**Comment by davestuart** [comment]
Thanks Greg, that worked for the Windows Forms but I'm still having issues with the Console App, I'll post that code in a minute with details on the execption. This is what I did to get the Windows Forms to work. I also removed the Timer code and the Form loaded in a few seconds.

`private async void StartUp()
{

	// Log in when the Form Opens.
	var apiKey = "apiKey";
	var apiToken = "apiToken";
	MakeTrelloConnection(apiKey, apiToken);


	_factory = new TrelloFactory();
	await GetBoard();
	await GetActions();

	TrelloTrawl();
}`

**Comment by davestuart** [comment]
This is the Console App Code. The rest of the code is identical to the Windows Forms App, but when I run this one I get the following exception in GetBoards at line "await _board.Lists.Refresh();" I found this page with helped with the Windows Forms issue: https://recaffeinate.co/post/how-to-await-console-application/ 

I've been banging my head for 3-4 days on this so I was hoping you can put me out of my misery? Thanks!

1 of 2
TypeInitializationException: The type initializer for 'Manatee.Trello.Json.DefaultJsonSerializer' threw an exception.
2 of 2
TypeLoadException: Method 'Handles' in type 'Manatee.Trello.Json.ActionTypeSerializer' from assembly 'Manatee.Trello, Version=4.0.0.0, Culture=neutral, PublicKeyToken=f502fcc17fc907d6' does not have an implementation.

        private static TrelloAuthorization _trelloAuthorization;
        private static TrelloFactory _factory;
        private static Board _board;

        public static void Main(string[] args)
        {
            try
            {
                var result = StartTrello().Result;
            }
            catch (ArgumentException aex)
            {
                Console.WriteLine($"Caught ArgumentException: {aex.Message}");
            }
        }
        private static async Task<string> StartTrello()
        {

            // Log in 
            var apiKey = "apiKey";
            var apiToken = "apiToken";
            MakeTrelloConnection(apiKey, apiToken);

            await GetBoard();
            await GetActions();

            RunTrelloTrawl();

            return "Completed!";
        }

**Comment by gregsdennis** [comment]
Did you update Manatee.Json?  Had another question with that.  You need to stay on v11 until I can update Manatee.Trello to use it (see open PR).

**Comment by davestuart** [comment]
Thanks, I did not know that! So after updating to Manatee.Json v11.04 and Manatee.Trell v4.1.1 the Console App is now working! If I have Release Watches ON will I get and e-mail when you release either of these Nuget Packages?

**Comment by gregsdennis** [comment]
I'm not sure about how Nuget subscriptions work.  Glad it's working for you.

**Comment by gregsdennis** [comment]
I've updated to Manatee.Json 12. Please see v3.2.1.

**Comment by davestuart** [comment]
Manatee.Json v12.0.3 and Manatee.Trello v4.2.3 Now works for me. Thanks!
