### ISSUE TITLE
Sometimes Code do not stop at await of board referesh call It retuns from the async method imidiatly 

### ISSUE THREAD

**Issue by azbvision** [gregsdennis/Manatee.Trello#329]
**Describe the bug**

**To Reproduce**
Please add test code or steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- .Net Target (Fwk 4.5, Std 1.3, or Std 2.0) 

**Additional context**

**Comment by gregsdennis** [comment]
@azbvision please add details to the description, not the title.

**Comment by gregsdennis** [comment]
You may be calling `Refresh()` too often.  There is a built-in and configurable rate limiting that will prevent excessive calls to the Trello API.  You can use `TrelloConfiguration.RefreshThrottle` to override this timing.

Alternatively, you can call `Refresh(true)` to explicitly force a call to the API.

**Comment by azbvision** [comment]
TrelloAuthorization.Default.AppKey = TrelloIds.AppKey;
            TrelloAuthorization.Default.UserToken = TrelloIds.UserToken;

            var board = new Board(TrelloIds.BoardId);
            await board.Refresh(true);

            var list1 = board.Lists[0];

            await Task.WhenAll(list1.Refresh());

            var cards = list1.Cards.ToList();

Here when it runs await board.Refresh(true); it never returns. But the same lines of code works in Another project of mine. Method return type is Task so so it keep on waiting, If I use Void return type it do not wait and skips all following lines and returns immediately.

**Comment by gregsdennis** [comment]
Why do you have the list refresh in a `Task.WhenAll()`?  You should just await that directly.

I'm not sure why it would be locking on `board.Refresh(true)`, but you definitely want a `Task` return type.

**Comment by azbvision** [comment]
Not working yet. The same code is working in another version of code.
Can you please access to my machine for a minute and have a look I have bee trying to figure it out for 
2 days now but still Unsuccessful.
Thanks

**Comment by gregsdennis** [comment]
Please join me [in Slack](https://join.slack.com/t/manateeopensource/shared_invite/enQtMzU4MjgzMjgyNzU3LWZjYzAzYzY3NjY1MjY3ODI0ZGJiZjc3Nzk1MDM5NTNlMjMyOTE0MzMxYWVjMjdiOGU1NDY5OGVhMGQ5YzY4Zjg) and we can discuss.

**Comment by azbvision** [comment]
I have joined. Thanks

**Comment by gregsdennis** [comment]
This was an async/await issue with Windows Forms.
