### ISSUE TITLE
Two Refresh() methods in a row do not populate lists

### ISSUE THREAD

**Issue by taxpayer** [gregsdennis/Manatee.Trello#330]
**Describe the bug**
I struggled about this for 2 days and I finally found out what's happening, so I'd like to share it. I'm not sure if this is really a bug or a "misuse" by myself. The fact is if I call two **Refresh()** methods in a row, for example, one for a card and another for its comments list, the **Comments** property of the card will be empty.

If I only call the **Refresh()** method from the card object, its comments (and other lists as well) will be populated.

**To Reproduce**
```
var factory = new TrelloFactory();
var card = factory.Card([Card Id]);

await card.Refresh();
await card.Actions.Refresh(); // If you comment this line, the result list below will be populated. Otherwise, it will be empty.

var result = new List<string>();
result.AddRange(card.Actions.Select(a => a.Id).ToList());

return result;
```

**Expected behavior**
I'm not sure, but I expected that the second Refresh(), even if not necessary (as I ended up understanding that it's not), it should not empty the list property being "refreshened".

**Desktop (please complete the following information):**
- .Net Core 3.1.1
 - Manatee.Trello 4.2.3 / ManateeJson 2.3.0

**Additional context**
Thanks again for the superb component! ;-)

**Comment by gregsdennis** [comment]
This is expected.  In the Trello API, comments are merely actions.  However, I thought that they were important enough to be separate, so I modeled it that way.  The trouble is that I can only request one at a time.  I figured comments would be more commonly wanted, so that's the default.  It's all controlled with the `Card.DownloadedFields` static property.

**Comment by taxpayer** [comment]
@gregsdennis but what's still not totally clear to me is why the second Refresh(), when called from the list property, clears the items that were read by the first Refresh().

Anyway, it was really just a question, the component is working as expected.

Thanks.
