### ISSUE TITLE
Can't seem to get the CheckList Items from a Card

### ISSUE THREAD

**Issue by davestuart** [gregsdennis/Manatee.Trello#331]
Hi Greg,

I'm sure this is not a bug but I cannot for the life of me figure out how to get the CheckList Items from a Card. This is what my code looks like. checkItems just returns the some properties and not the collection I'm looking for, which should have 10+ items in it. This is kind of an urgent request from a client so I was hoping you could point me in the right direction. Thanks!

BTW, the 2 await method are just calling .Refresh() on the Card and CheckList

foreach (var list in _board.Lists)
{
	
	listName = list.Name;
	listId = list.Id;
	_list = new List(listId);

	await RefreshList();
	
	foreach (var card in list.Cards)
	{
		cardName = card.Name;
		cardId = card.Id;
		_card = new Card(cardId);

		

		if (listName == "Vessels")
		{

			await RefreshCard();
			await RefreshCheckLists();

			var checkItems = _card.CheckLists.Refresh();
		   
		}
	}
}

**Comment by gregsdennis** [comment]
The hierarchy is

```
Card
- CheckList
  - CheckItem
```

A card can have multiple checklists, each with multiple check items.

It looks like your `checkItems` variable is actually a `CheckListCollection`.  You'll need to pick the list you want and enumerate that to get to the items.

**Comment by gregsdennis** [comment]
I also have an example [here](https://gregsdennis.github.io/Manatee.Trello/examples/delete-checkitem.html) where I delete a check item after isolating it.

**Comment by davestuart** [comment]
Thanks for the quick reply Greg! I followed your example to a tee but still have an empty CheckListCollection. I really don't know why it's empty when I can see 4 CheckLists in the Card. Here is some code I have been using for this. 

            var card2 = _factory.Card("5db764ef9bbfbc36c521b35a");
            // This await ends the code for some reason?
            await card2.Refresh();
            var checkList2 = card2.CheckLists;

            foreach (var list in _board.Lists)
            {
                
                listName = list.Name;
                listId = list.Id;
                _list = new List(listId);
                
               
                foreach (var card in list.Cards)
                {
                    cardName = card.Name;
                    cardId = card.Id;

                    // Just trying to look at the Card individually
                    // This gets an empty the Card for some reason.
                    _card = new Card(cardId);
                    await _card.Refresh();

                    if (listName == "Vessels")
                    {
                        if (cardName == "V5232")
                        {
                            // I can't call the await here as it just ends the code run
                            // I think this is because I'm in an iteration of card!?
                            //await card.CheckLists.Refresh();
                            var checkLists = card.CheckLists;

                            foreach (var checkList in checkLists)
                            {
                                checkListItemId = checkList.Id;
                                checkListItemName = checkList.Name;
                                var checkListItemItems = checkList.CheckItems;
                            }
                        }

                    }
                }
            }

**Comment by gregsdennis** [comment]
Have you changed the default setting for `Card.DownloadedFields`?

**Comment by davestuart** [comment]
Not that I know about. The client has set this up using the Trello interface so I doubt that has changed. How can I check if the defaults have changed?

**Comment by davestuart** [comment]
This is the result of the Card.DownloadedFields property: 
Manatee.Trello.Card.Fields.Badges | Manatee.Trello.Card.Fields.Board | Manatee.Trello.Card.Fields.Checklists | Manatee.Trello.Card.Fields.DateLastActivity | Manatee.Trello.Card.Fields.Description | Manatee.Trello.Card.Fields.Due | Manatee.Trello.Card.Fields.IsArchived | Manatee.Trello.Card.Fields.IsComplete | Manatee.Trello.Card.Fields.IsSubscribed | Manatee.Trello.Card.Fields.Labels | Manatee.Trello.Card.Fields.List | Manatee.Trello.Card.Fields.ManualCoverAttachment | Manatee.Trello.Card.Fields.Name | Manatee.Trello.Card.Fields.Position | Manatee.Trello.Card.Fields.ShortId | Manatee.Trello.Card.Fields.ShortUrl | Manatee.Trello.Card.Fields.Url | Manatee.Trello.Card.Fields.Actions | Manatee.Trello.Card.Fields.Attachments | Manatee.Trello.Card.Fields.CustomFields | Manatee.Trello.Card.Fields.Members | Manatee.Trello.Card.Fields.Stickers | Manatee.Trello.Card.Fields.VotingMembers

**Comment by gregsdennis** [comment]
It'd be something you' explicitly set in the code.  It controls what fields Manatee.Trello downloads.  By default, it's everything except comments (because comments are actions, and I opted to download actions).  If you haven't changed it, then it should be downloading the checklists.

Also, I'm confused as to why awaiting a refresh would cause your code to end.  Maybe an exception is being thrown that you're not catching but is killing the thread.

**Comment by davestuart** [comment]
Ah, I got it! I was using `public static async **void** GetTrelloObjects()` rather than `public static async **Task** GetTrelloObjects()` for the method signature. That is why the await was crashing the code. I could not even catch the exception inside a try-catch. 

So thanks for your support with this. It certainly helped my dig deeper. Have a great day!

**Comment by gregsdennis** [comment]
okay.  Glad you got it figured out.
