### ISSUE TITLE
Organisation.Boards.Refresh() throws error

### ISSUE THREAD

**Issue by harrison-childs** [gregsdennis/Manatee.Trello#332]
When executing Refresh() on organisation.Boards an ArgumentException is thrown.

`var factory = new TrelloFactory();`
`var me = await factory.Me();`
`var org = me.Organizations.FirstOrDefault();`
`await org.Boards.Refresh();`

**To Reproduce**
Run the above code and the error message should be: 
ArgumentException: Requested value 'enterprise' was not found.

This exception was originally thrown at this call stack:
	System.Enum.TryParseByName(System.RuntimeType, string, System.ReadOnlySpan<char>, bool, bool, out ulong)
	System.Enum.TryParseInt32Enum(System.RuntimeType, string, System.ReadOnlySpan<char>, int, int, bool, bool, System.TypeCode, out int)
	System.Enum.TryParse(System.Type, string, bool, bool, out object)
	System.Enum.Parse(System.Type, string, bool)
	Manatee.Json.Serialization.Internal.Serializers.EnumNameSerializer.Deserialize(Manatee.Json.Serialization.DeserializationContext)
	Manatee.Json.Serialization.Internal.Serializers.DefaultValueSerializer.TryDeserialize(Manatee.Json.Serialization.ISerializer, Manatee.Json.Serialization.DeserializationContext)
	Manatee.Json.Serialization.Internal.Serializers.SchemaValidator.TryDeserialize(Manatee.Json.Serialization.ISerializer, Manatee.Json.Serialization.DeserializationContext)
	Manatee.Json.Serialization.JsonSerializer.Deserialize(Manatee.Json.Serialization.DeserializationContext)

**Details:**
 -  .Net Core 3.1 Azure Function App.
 -  Referencing the Manatee.Trello Nuget package version 4.2.3

**Comment by gregsdennis** [comment]
Looks like you probably found an org type that I'm not aware of.  (I don't have enterprise offerings, so it's hard to develop for them.)

If you can capture the JSON coming over the API and post it, then I can confirm what the value belongs to.  (Don't forget to sanitize it first.)

Thanks for the report.

**Comment by harrison-childs** [comment]
[Trello board object.txt](https://github.com/gregsdennis/Manatee.Trello/files/4288052/Trello.board.object.txt)

Hi there, I've use Fiddler to extract an example Board object out of the org.Boards.Refresh() method. Please note I've redacted unimportant arrays and have replaced sensitive strings, however if you need more information please let me know. 

I believe the part you are interested in us under organization.prefs.boardVisibilityRestrict and boardDeleteRestrict

**Comment by gregsdennis** [comment]
Thank you.  That helps.  I'll work through this and push an update.

**Comment by gregsdennis** [comment]
Hm... That error comes from Manatee.Json when trying to deserialize an enum by name and it gets a value that's not listed in the enum.  The `enterprise` in `boardVisiblityRestrict` is a property, so that's a different issue.  (I don't have that property in my model; I'll add that as well.)

Can you look through your uncensored capture and see if there's an `enterprise` somewhere as a value, please?

**Comment by harrison-childs** [comment]
[Trello board object 2.txt](https://github.com/gregsdennis/Manatee.Trello/files/4292346/Trello.board.object.2.txt)

Hi again, find attached another example where I've located the only places where `enterprise` have been used as values.

This time the points of interest are: 
- prefs.permissionLevel
- actions[0].data.board.prefs.permissionLevel

Hope this helps.

**Comment by gregsdennis** [comment]
Yep.  The enum is `IJsonBoardVisibilityRestrict`.  I'll add the `enterprise` value and publish to unblock you.  It also looks like there are some other properties I can incorporate in the models, but that'll take longer.

**Comment by gregsdennis** [comment]
@harrison-childs v4.3.0 should be released soon.  This should fix the problem.
