### ISSUE TITLE
Empty custom field names

### ISSUE THREAD

**Issue by Blood13** [gregsdennis/Manatee.Trello#338]
Hello.
I'm using .net core 3.1 on windows.
I'm trying to get card custom fields. It looks like this:

```
[Fact]
public async void GetCardById()
{
    TrelloAuthorization.Default.AppKey = "[my_app_key]";
    TrelloAuthorization.Default.UserToken = "[my_user_token]";

    var card = new Card("[test_card_id]");

    await card.Refresh();
    await card.CustomFields.Refresh();
}
```
I've got list of custom fields, but it's `Definition.Name` field is null.
I've noticed, that on deserialization, when
`Definition = obj.Deserialize<IJsonCustomFieldDefinition>(serializer, "idCustomField");`
executed, `idCustomField` isn't object, but string.
```
switch (json.Type)
    {
        case JsonValueType.Object:
            var obj = json.Object;
            Id = obj.TryGetString("id");
            Board = obj.Deserialize<IJsonBoard>(serializer, "idBoard");
            FieldGroup = obj.TryGetString("fieldGroup");
            Name = obj.TryGetString("name");
            Pos = obj.Deserialize<IJsonPosition>(serializer, "pos");
            Type = obj.Deserialize<CustomFieldType?>(serializer, "type");
            Options = obj.Deserialize<List<IJsonCustomDropDownOption>>(serializer, "options");
            Display = obj.Deserialize<IJsonCustomFieldDisplayInfo>(serializer, "display");
            ValidForMerge = true;
            break;
        case JsonValueType.String:
            Id = json.String;
            break;
    }
```
Program switch to `JsonValueType.String` route, and `Definition.Name` stays empty. 
Example in official [docs](https://developer.atlassian.com/cloud/trello/rest/#api-cards-id-customFieldItems-get) says that `idCustomField` is string (`"idCustomField": "5abbe4b7ddc1b351ef961414",`).

Is trello api changed, or i'm doing something wrong?

**Comment by gregsdennis** [comment]
The API only returns IDs for the definitions when fetching them from the cards.  If you refresh the `board.CustomFields` property first, those entities will be cached, and you'll get the cached versions when refreshing the card data.  That should get you your name.

**Comment by Blood13** [comment]
@gregsdennis thank you kind sir! You are awesome!
