### ISSUE TITLE
Cannot retrieve CustomField value

### ISSUE THREAD

**Issue by umadair** [gregsdennis/Manatee.Trello#340]
**Describe the bug**
I have a Visual Basic project where I don't seem to be able to retrieve the value of a CustomField. The Value property shows up in the watch variables in debug mode, but the IDE doesn't recognize it and gives an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/10373542/89450106-03c30e80-d728-11ea-8cb4-aea1b9c3a567.png)

![image](https://user-images.githubusercontent.com/10373542/89450129-0cb3e000-d728-11ea-9d57-c4b0ecd46a4e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- .Net Target Framework 4.7.2
 - Version Manatee.Trello version 4.3.0
- Visual Studio 2017

**Comment by gregsdennis** [comment]
The `.Value` property is only available on the typed field. You'll need to cast it first.

**Comment by umadair** [comment]
Typed as in declaring custField as variable? Because I do have it declared as:

`Dim custField As Manatee.Trello.CustomField`

**Comment by gregsdennis** [comment]
`CustomField` is abstract. It has 5 subclasses, each with its own value.  You have to cast to the right class before you have access to the property you want.

**Comment by umadair** [comment]
Thank you for that clarification! That makes more sense.
