### ISSUE TITLE
CreateCheckItem does not have a supported actionType

### ISSUE THREAD

**Issue by RonaldKruizinga** [gregsdennis/Manatee.Trello#342]
**Describe the bug**
```TrelloInteractionException: Trello has reported an error with the request: ActionType 'createCheckItem' is not a recognized value.  It may be a new value that Trello introduced since this version of Manatee.Trello.```

The above error occurs when a checklist item is added to a card that is being listened to through a webhook. I also cannot find this event in the ActionType struct in the documentation.

It would be nice if it could be added to the library.

**To Reproduce**
Please add test code or steps to reproduce the behavior:
1. Go to a board that is being listened to.
2. Add a checklist item to a checklist.
3. TrelloProcessor.ProcessNotification breaks.

**Expected behavior**
The event being handled or at least not throwing an exeption.

**Desktop (please complete the following information):**
 - OS: Windows 10
- .Net Target (Core 3.1)
- Manatee version 4.3 (Latest on NuGet)
I hope you have time to look into this.
Have a nice day!

**Comment by aramdata** [comment]
I have this problem too

**Comment by gregsdennis** [comment]
Hey, thanks for reporting this.  I'm not actively supporting this anymore, but if you want to create a PR, I'll merge it in, so a new version will publish.

**Comment by gregsdennis** [comment]
Published as part of ☝️.  Please see v4.4.0
