### ISSUE TITLE
Question: Single rest call card creation?

### ISSUE THREAD

**Issue by patrickklug** [gregsdennis/Manatee.Trello#343]
Is it possible with this library to create a card with name, description, position and ideally attachments, without having separate API calls for each?

The below call seems to create the card first with only the title, then update the position and the description in a separate call.

```
var list = _factory.List(LIST_ID);
var card = await list.Cards.Add(title);
//set to top
card.Position = new Position(1);
card.Description = body;
```

Adding attachments will then also creates a separate call each:

```
await card.Attachments.Add(data, label);
```

I'd really want all this to happen in an atomic operation.

**Comment by gregsdennis** [comment]
The `Add()` method has a number of optional parameters you can use.  Any sub-entities will require separate calls.

https://github.com/gregsdennis/Manatee.Trello/blob/master/Manatee.Trello/Contracts/ICardCollection.cs#L13-L27

**Comment by patrickklug** [comment]
Wow, not sure how on earth I missed this... Thanks for the help!
