### ISSUE TITLE
Setting Card.DueDate goes to the day before

### ISSUE THREAD

**Issue by saulosag** [gregsdennis/Manatee.Trello#35]
Hi, I'm having problems setting the dueDate of a card.
```
var serializer = new ManateeSerializer();
TrelloConfiguration.Serializer = serializer;
TrelloConfiguration.Deserializer = serializer;
TrelloConfiguration.JsonFactory = new ManateeFactory();
TrelloConfiguration.RestClientProvider = new Manatee.Trello.WebApi.WebApiClientProvider();
TrelloAuthorization.Default.AppKey = "my app key";
TrelloAuthorization.Default.UserToken = "my user token";
var learningBoard = new Board("my board id");
string listId = learningBoard.Lists.First().Id;
var list = new List(listId);
var member = list.Board.Members.First();
var card = list.Cards.Add("test card 2");
card.DueDate=new DateTime(2016,07,21);
```
When running this snippet the dueDate on the card is changed to 2016,07,20 at 21:00. I tried with other Dates and it always gives the day before at the same hour. Is this expected and documented somehwere? Sorry if I missed something, just starting to use this API.

**Comment by saulosag** [comment]
Tried getting the card and changing dueDate using the Card object resulted in the same issue.
`var card = new Card("my card id");
            var date = new DateTime(2016,7,19);
            Console.WriteLine(date);
            card.DueDate = date;`

**Comment by gregsdennis** [comment]
Hey there, @saulosag.  Sorry for the delayed response.

I'll create a test in my app to see if I can replicate what you're seeing.

**Comment by gregsdennis** [comment]
Replicated.

Looking at the values that Trello is returning, it looks like they've changed their `DateTime` serialization format.  It used to be somewhat unformatted with an implied EST time zone, but now it looks like they're sending as UTC.  This is definitely part of the problem.  I'll get confirmation from Trello.

**Comment by saulosag** [comment]
Thank you for replying, I'll wait further responses.

**Comment by gregsdennis** [comment]
Please see Manatee.Trello.ManateeJson v1.5.1.
