### ISSUE TITLE
Adding Attachments with URL

### ISSUE THREAD

**Issue by AdamSmithson** [gregsdennis/Manatee.Trello#36]
Adding an attachment to a card with a url always throws an exception.

Starting on line 78 of AttachmentCollection.cs in Manatee.Trello, I found this code.

    var errors = new List<string> 
    { 
        NotNullOrWhiteSpaceRule.Instance.Validate(null, url), 
         UriRule.Instance.Validate(null, url) 
    }; 
    if (errors.Any()) 
        throw new ValidationException<string>(url, errors);

the null values returned by the Validate rules still count as a value in the list for errors.Any(), thus the exception always gets thrown.  Should be "if (errors.Any(x => x != null))"

Thanks for the work put into this project.

Manatee.Trello 1.11.1 Manatee.Trello.ManateeJson 1.5.1 Manatee.Json 4.0.2 Manatee.Trello.WebApi 1.0.4 .Net framework version 4.5

**Comment by gregsdennis** [comment]
Thanks for reporting.  I'll have it fixed and pushed to Nuget tonight.

**Comment by gregsdennis** [comment]
Please see v1.12.0 for the fix.  Thanks!

**Comment by AdamSmithson** [comment]
Thanks!  Working great!
