### ISSUE TITLE
Support for custom fields

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/Manatee.Trello#38]
Trello now supports custom fields through a PowerUp.  This feature is getting enough attention that it _must_ be implemented.

**Comment by ronwarner** [comment]
Please forgive me for posting this here, which I know isn't the right place.  I just want to ask if you have a place where questions about the library can and should be asked, and if there is any documentation out there for proper usage of the library's exposed classes.

**Comment by gregsdennis** [comment]
See branch [feature/power-ups](https://github.com/gregsdennis/Manatee.Trello/tree/feature/power-ups).

**Comment by gregsdennis** [comment]
Copying Trello support email regarding Power-Ups data

>Hey Greg,

>We have a bit more information about data storage for Power-Ups here, under the "Data Storage" section: https://developers.trello.com/power-ups/topics.

>What we currently expose via the API, though readonly at this moment, is: 

>`/1/boards/[id]/pluginData`
>`/1/cards/[id]/pluginData`

>Those both allow access to the shared visibility data at that scope (boards or cards). Power-Ups can store data on cards at the 'card' scope, or boards, or orgs (teams). Where they choose to store what data is entirely up to the Power-Ups themselves, so accessing the data via the API does require an understanding of how the Power-Up is working.

>I know this may be less than ideal. Data storage for Power-Ups is something that we are currently looking into exposing a bit more of via the API, so hopefully in the future we will be able to standardize this a bit more.

>All the best,

>Mercer
>The Trello Team

**Comment by gregsdennis** [comment]
Published Manatee.Trello.CustomFields.

**Comment by gregsdennis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Card](https://trello.com/c/KHKms82H/9-card)
