### ISSUE TITLE
Description not being sent to trello when creating being set after card create

### ISSUE THREAD

**Issue by captain345** [gregsdennis/Manatee.Trello#44]
I've got the following code

```c#
            Card newCard;

            if (storyToAdd.Size.HasValue)
            {
                newCard = _boardList.Cards.Add($"({storyToAdd.Size}) {storyToAdd.Title}");
            }
            else
            {
                newCard = _boardList.Cards.Add(storyToAdd.Title);
            }
            
            newCard.DueDate = storyToAdd.NeededBy;

            AddStoryDetailsToCard(newCard, storyToAdd);

            newCard.Description = CreateDescriptionWithMarkDown(storyToAdd);

            TrelloProcessor.Flush();
```

When adding the description to the new card it will sometimes forget to update the card with that information. Adding comments works, and can be seen in real time however it seems like adding a description does nothing. Surrounding the code in a try catch also returns no erros.

Any Ideas?

# Update
I'm an idiot it's because the dueDate was being set incorrectly to DateTime.MinValue and as such was causing an issue with the context.

Sorry about that

**Comment by gregsdennis** [comment]
Glad you found the problem.  I'm still interested in what happened with the due date, though.  You say `DateTime.MinValue` causes problems inside the context?  I'll see if I can make that a bit more friendly to debug.

**Comment by gregsdennis** [comment]
I"m also concerned that it didn't throw an error upon receiving a 400 response.  I'll fix it as part of #45.

**Comment by gregsdennis** [comment]
Also fixing an issue with the WebApi package:  Receiving a non-successful status code should throw an exception to let the client know that something went wrong.

**Comment by captain345** [comment]
One thing i did notice when doing this is that i was unable to just create a card object with the values i needed is that something that would potentially fix the issue?

**Comment by gregsdennis** [comment]
If that's something you'd find useful, I can look into it.  Please create another issue and I'll mark it as an enhancement.

**Comment by gregsdennis** [comment]
Please update Manatee.Trello, Manatee.Trello.ManateeJson, and Manatee.Trello.WebApi to latest.
