### ISSUE TITLE
Allow addition all of properties when adding a card to a list.

### ISSUE THREAD

**Issue by captain345** [gregsdennis/Manatee.Trello#47]
Currently creating a card object requires all the properties to be filled. I think it'd be useful to allow us to create the object with certain fields such as title, description, comments. This would mean that as a developer we could avoid having fields not set correctly as we'd already have the Card built up.

**Comment by gregsdennis** [comment]
Thanks.  I'll have to do some research on this.  There are a few properties which are mandatory.  I think that's how I set up the `Add()` method.  This will likely manifest as adding a bunch of optional parameters.

I'll also look at doing this for the other entity types.

**Comment by gregsdennis** [comment]
[The Trello API docs for adding cards](https://developers.trello.com/advanced-reference/card#post-1-cards)

It looks like the options are limited as to what can be added at creation, but I'll add them as optional parameters in the method.  Shouldn't be a breaking change.
