### ISSUE TITLE
Add PropertyChanged support

### ISSUE THREAD

**Issue by scrubs767** [gregsdennis/Manatee.Trello#54]
Currently propertychanged is fired for the card object when it gets updated, but if you bind to properties on the card they do not fire a propertychanged event. For instance if you bind an itemscontrol to card.attachments the application is not notified that a change has occurred.

A simple way to solve this is to use an observable collection, this will notify if an item is added or deleted, but wont notify if a property on an object in the collection has changed, not sure if that is needed though.

This is an issue with all the collections on a card I am binding too, I'm not sure if this is true for other properties on Card.

**Comment by scrubs767** [comment]
I currently have a work around for this by wrapping the Card class and exposing its properties through my view model. In the view model I listen for the updated event and just fire propertychanged for everything I'm bound to, however this is not desirable as it causes everything to re-evaluate its bindings instead of what has changed.

**Comment by gregsdennis** [comment]
I like the idea, but I need to investigate whether `INotifyPropertyChanged` is a concept used outside of WPF (the only place I've used it).  If it's a more general idea, then I don't have a problem making those cards conform.  However if it's something that's explicitly tied to WPF, I'd prefer that three entities in Manatee.Trello be treated as domain- or data-access-level classes and you create specific view models to represent them (as you've done in your workaround).

**Comment by gregsdennis** [comment]
SO has a good [post](http://stackoverflow.com/q/7347984/878701) with several decent opinions on using `IPropertyChanged`.  The general consensus is that individual events should be created.

That said, the `Updated` event as it's currently implemented is effectively a more strongly typed version of `PropertyChanged` anyway. 

I think this would be a good change.  I'll also implement `INotifyCollectionChanged` on the collections.  Finally, `Updated` will be marked obsolete.

**Comment by scrubs767** [comment]
I understand, yes property changed events are for wpf, I don't see them being used elsewhere, but they can be. It's just a software pattern that uses events to let other software know a property has changed. Wpf uses it for databinding.

**Comment by gregsdennis** [comment]
In reworking this for a bit, I just realized that `Updated` is *not* the same as `PropertyChanged`.  Specifically, a single `Updated` notifies that one *or more* properties have changed; `PropertyChanged` only notifies of a *single* property.  This means that an entity would have to raise `PropertyChanged` for each property.

I like the single event approach for this library.

---

I do however like the idea of having view-model-compatible entities.  It may be beneficial to publish these in a separate library.  @scrubs767 is that something you'd be interested in?  I don't imagine such a project would take too long.

**Comment by scrubs767** [comment]
I would have to take a look. Looking at Manatee.Trello as a black box, is there a way to tell what has changed?

Some questions:
From what I understand, the Card requests an update, how does it know a change has occurred? 
When a change occurs does it just make a new request for all the information again, or does it just receive the updates?

Worst case scenario, I could wrap Card and listen for updates, then poll each property for changes including every property on every object in a collection.

**Comment by scrubs767** [comment]
Ok, So I spent some time looking at how it works, from what I can tell an application will have a card object, after the cache timeout has expired, any access to the card will force an update and the update event is fired. All the information for the card is reloaded into the card again.

The update process stated above does not happen unless the card is accessed in some way, if its just sitting in memory and nothing tries to read (possibly write?) a property, then the update event will never get fired.

Is this all correct?

**Comment by scrubs767** [comment]
On a side note, in SynchronizationContext.cs line 195 is the following code:
>if (Equals(json, default(TJson)) || ReferenceEquals(json, Data))
>    return Enumerable.Empty<string>();

I think this is trying to see if the json returned is different and just return without any processing, not 100% sure though. If this is the case, and is meant to not process any more data if no new card data (or other object data) is available, its not working properly as the object are never equal.

If that is not the purpose I would suggest adding code to compare the json and not process the data for performance reasons. It may or may not be relevant though. Just something I noticed.

**Comment by gregsdennis** [comment]
@scrubs767 have you read through the wiki?  It explains the updating strategy.  And yes, you're correct.

That line is really just a sanity check to ensure that it's not merging a JSON object onto itself.  It *has* been a while since I wrote that.  It may be worth reviewing that code again to see if I can make it more efficient.

**Comment by gregsdennis** [comment]
@scrubs767 I'm closing this issue for now.  If you'd like me to, I can work up a view model package that supplies notifying entities.  Otherwise I think your workaround is the best approach.

**Comment by scrubs767** [comment]
I think you should close it, and I think you should not work on this because in order for this to work as expected from a wpf developer, any and everything that a developer is listening to would need to automatically refresh on a pretty short timer. This would be a whole bunch of network traffic, most of which probably wont be needed. It would be better to let the developer decide when to update.

A much better way to support this would be to add an event that get fired when a property gets updated on an object, this could be done in the synchronizationcontext (maybe mergeproperties, not sure though, I didnt get a chance to look at it), throw one event listing all the properties updated. This way a developer could call update on something, and their bindings would still work properly. This event should only get fired if the properties are actually different.

Here is an example:
A window is displayed showing the card information, the developer added a timer to refresh the card every 60 seconds. This window has bindings to properties on the card. Someone through the web interface added a label and moved its list. When the timer kicks off and the card is refreshed an event is fired and the property names are added to the eventargs. Now the wpf developers code can listen for that event and fire off the appropriate propertychanged events. The UI updates itself.

A developer could use that architecture in any way because you arent tying yourself to WPF, that type of thing could be used in any application, consol, WPF WinForms droid...(I know nothing about IOS), but its plain c#.

**Comment by scrubs767** [comment]
I left that comment in place, but after writing it and thinking about it for a bit, none of its needed really. Its just as easy to run a timer calling updated and then throwing a property changed on that card. 

The same thing could be said for a list of cards (or anything) return from a search, just rerun the search again.
