### ISSUE TITLE
New Action types

### ISSUE THREAD

**Issue by Hagansson** [gregsdennis/Manatee.Trello#55]
Hello I run following code:
 
Manatee.Trello.Action createBoard = null;
                //Check for any board create actions 
                try
                {
                    createBoard = board.Actions.Where(a => a.Type == ActionType.CreateBoard &&
                        a.Date.Value.ToUniversalTime() > DateTime.UtcNow.Subtract(TimeSpan.FromHours(hours)) &&
                        a.Date.Value.ToUniversalTime() < DateTime.UtcNow).FirstOrDefault();
                }
 
And i get this errors:
Requested value 'enablePlugin' was not found.
Requested value 'disablePlugin' was not found.
 
Why did I get this errors and how should I fix that?

Best regard: Hagansson

**Comment by gregsdennis** [comment]
These aren't any fault of yours.  They're error messages that indicate that a particular message type hasn't been coded. 

I'll have to update the package.  Are you getting an exception?

**Comment by Hagansson** [comment]
Can i send you a picture of the error?
I dont get any good error message but i have take a screenshot of this

**Comment by gregsdennis** [comment]
You can go on the gitter room and post the picture there.  Is this blocking your development?  I can probably get to this tomorrow.

**Comment by Hagansson** [comment]
My system id down, becuse of this error, but i Can Wait to tomorrow

**Comment by gregsdennis** [comment]
@Hagansson I've resolve the issue.  I'm building the Nuget packages now.  Please use:

- Manatee.Trello v1.15.0
- Manatee.Trello.ManateeJson v1.7.0

They will be available shortly.
