### ISSUE TITLE
Wiki link - fixed in Pull Request

### ISSUE THREAD

**Issue by TamaHobbit** [gregsdennis/Manatee.Trello#57]
I clicked a link in Getting Started, which 404'd because you renamed the page from Config to Configuration, I guess. Then, in the next commit, I fixed a minor typo; "communication is uncountable".

Since GitHub doesn't support Pull Requests in wiki's, I'm following [this recommendation](http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github#11481887) and making an issue.

Just fetch [this branch](https://github.com/TamaHobbit/ManateeTrelloWiki/tree/bugfix/typos) of my fork, and merge in either bugfix/typos or, if you only want the broken link fixed, f919843eac2d.

**Comment by gregsdennis** [comment]
Is this the pull request you created, or another fix?

**Comment by TamaHobbit** [comment]
GitHub doesn't support Pull Requests in wiki's.
It is a pull request in the sense that I am asking you to go into your wiki repository and pull [this remote](https://github.com/TamaHobbit/ManateeTrelloWiki/tree/bugfix/typos), and merge it into master, but it is **not** a github PR with a nice easy green "accept" button.

**Comment by gregsdennis** [comment]
Nifty!  I didn't know I could pull from a different remote.

Anyway... done.  Thanks!
