### ISSUE TITLE
Unable to edit comment value

### ISSUE THREAD

**Issue by Serrarthu** [gregsdennis/Manatee.Trello#59]
I am unable to edit the value of a comment using the Manatee.Trello methods.

```
Action comment=new Action;
//comment.Data.Value is read-only
comment.Data.Text="some random string"
```

This yields the following error:

```
ValidationException`1: 'some random string' is not a valid value.
Manatee.Trello.Internal.Field`1[System.String].Validate (System.String value)
Manatee.Trello.Internal.Field`1[System.String].set_Value (System.String value)
Manatee.Trello.ActionData.set_Text (System.String value)
MyClass.MyMethod (System.String newCom) (at Myclass.cs:29)
```

This also seems to reset the tags attached to the card, both inside Trello and inside my application. The comments are unchanged however.

**Comment by gregsdennis** [comment]
I found the reason for the validation error.  I had some logic backwards.

However, fixing that exposed another issue.  I'm working on resolving that.  Once done, I'll have an update for you.

**Comment by gregsdennis** [comment]
I was able to fix the issue.  It's currently in branch **bug/issue59**.  I'll merge it when I have a few other new issues worked out.

**Comment by gregsdennis** [comment]
Please see Manatee.Trello v1.16.0, now available on Nuget.
