### ISSUE TITLE
Wiki needs more explicit documentation

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/Manatee.Trello#62]
The current wiki information is nice but somewhat anecdotal.  It needs some hard documentation.

**Comment by mathieuchateau** [comment]
Can we help ?

**Comment by gregsdennis** [comment]
I welcome help on the wiki. I'm not even sure what kind of docs I want.

**Comment by re-al-7** [comment]
Maybe a Demo Project would provide a better explanation of the library.... or not?

**Comment by ronwarner** [comment]
I find the style used to document the .Net class library to be very helpful.  That is, a blurb to describe each public member, along with very brief usage examples here and there.  Types of exceptions that can be expected from certain situations is also helpful.  Old and new versions for a random class:

[System.Data.DataSet Old Version](https://msdn.microsoft.com/en-us/library/system.data.dataset(v=vs.110).aspx)
[System.Data.DataSet New Version](https://docs.microsoft.com/en-us/dotnet/api/system.data.dataset?view=netframework-4.7.1)

**Comment by gregsdennis** [comment]
@ronwarner I was thinking along those lines as well.  I just need to do it, but my time's been limited.  Also, there may be better tools than the wiki.

**Comment by gregsdennis** [comment]
I have started an API folder and updated the side bar.  I think this is the direction we want to go.

**Comment by gregsdennis** [comment]
This is great and all, but it's going to be a pain to manually update.  I think I'm going to start looking for a way to update this automatically.

**Comment by gregsdennis** [comment]
Did someone mention a [new project](https://github.com/gregsdennis/AutoWiki)?

**Comment by mathieuchateau** [comment]
lol

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2018-02-10 5:57 GMT+01:00 Greg Dennis <notifications@github.com>:

**Comment by gregsdennis** [comment]
I think the generator is ready.  I just need to write the templates and make sure my XML comments are good.

**Comment by gregsdennis** [comment]
@mathieuchateau @ronwarner @re-al-7 would everyone please review the API-Actions and API-Boards.  Is the format good, or is it too much?  I can fix the specific content through the XML comments.

I do have a few things I need to work on in the generation, like listing if a member is static and linking member types to its wiki entry, but I think it's mostly there.

**Comment by gregsdennis** [comment]
I've removed the code formatting from API-Boards. I think it's a bit easier on the eyes.

**Comment by ronwarner** [comment]
@gregsdennis Upon a cursory click through of some of the pages, this looks great.  I'll go through a bit deeper and see if anything of particular note comes up.

**Comment by gregsdennis** [comment]
I'm going to close this for now. I think the only additional documentation could be more of an anecdotal nature.  Unfortunately, I need a better writer than myself to do it.

**Comment by ronwarner** [comment]
I just wanted to let you know, if I can get some time (always a challenge!), I hope to contribute to it, and maybe pull down the doc generator and see if I see any opportunities for formatting improvements.
