### ISSUE TITLE
Retry on server errors (5XX and 429)

### ISSUE THREAD

**Issue by gioccher** [gregsdennis/Manatee.Trello#63]
Hi,
first thanks for this library, it's a big time saver!

The library should have an option to retry the requests when trello returns errors such as 500 and 429 (rate limit).
Especially on rate limit errors, it should use a truncated exponential backoff retry strategy.

Unless I'm missing something, currently the burden is on the library user to surround every Manatee.Trello call that might generate a HTTP request in try/catch and retry.

**Comment by gregsdennis** [comment]
I can add this as a configuration point.  Likely, it will be something like the ability to set which response codes to retry.

**Comment by gregsdennis** [comment]
Please see branch **feature/response-code-retry** for the resolution of this.  I will merge in and publish an update soon.  This will update both the main library and the rest client libraries.

**Comment by gregsdennis** [comment]
Please see Manatee.Trello v1.16.0, Manatee.Trello.RestSharp v1.3.0, and Manatee.Trello.WebApi v1.1.0, now available on Nuget.

**Comment by gioccher** [comment]
Thank you, but there should be a delay before retrying.
If the server returns a 500 errors, it might take some time for it to realize it's doing something wrong, heal, and start processing things again correctly.
If the server returns a 429 error, retrying immediately will only make things worse.


What about this: expose a delegate/event in the configuration class that gets called any time an unsuccessful response is returned (a network or server exception is thrown, or trello returns an error message) .
This provides the response to the user, and includes the exception thrown if any, along with the number of previous retries. The user can then specify how much time to wait before retrying (in milliseconds), or not to retry.

**Comment by gregsdennis** [comment]
I was thinking on this.  It seems that a delegate may not be the easiest solution for most devs, but it *is* the most flexible option.

So I think I'll add the delegate option as well as a timespan for a delay.  The timespan delay will occur if no delegate is present.

Regarding passing the response, it'll have to be of type `IResponse` and the implementor will need to cast as appropriate based on the particular rest package used.

Thoughts?

**Comment by gregsdennis** [comment]
@gioccher, please see branch **feature/custom-retry** and let me know your thoughts.

**Comment by gioccher** [comment]
Hi, I haven't had a chance to try it yet but only took a look at the commit and it looks good.
It still is retrying on a fixed time interval instead of the more server-friendly exponential backoff, but the user can implement that (or when I have a moment I might submit a pull request with that)

**Comment by gregsdennis** [comment]
I've merged in the code as is.  Unless you have an urgent need, I'll publish it when I have a few other issues resolved, hopefully within the next week or so.

**Comment by gregsdennis** [comment]
Please see version 1.17.0 for the customizable functionality.
