### ISSUE TITLE
Issue retrieving preferences of a board obtained by searching

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/Manatee.Trello#68]
When searching for a board, it seems that the preferences object is not populated.  To be clear, the object is there, but all properties are null.

Source: [SO question](http://stackoverflow.com/q/42675582/878701)

    Board myboard =  new Search(SearchFor.TextInName("MyAwesomeBoard"), 1, SearchModelType.Boards)
        .Boards.FirstOrDefault();
    var boardColor = myboard.Preferences.Background.Color;
    var boardImg = myboard.Preferences.Background.Image;

**Comment by gregsdennis** [comment]
Created branch **bug/issue-60-preferences-from-search**.

**Comment by gregsdennis** [comment]
So I found the issue.  I was expecting a search API call to return just the IDs of objects, but for boards (at least) it was returning objects.  This caused the library to think that the board was completely downloaded and needed to be refreshed.  The fix was to manually mark the board to be refreshed.

Secondarily, when the context was expired, any linked contexts still thought that they were current.  The fix was to extend the expiration to the linked contexts as well.

**Comment by gregsdennis** [comment]
I will have an update available on Nuget within the next week or so.  Please let me know if an update is more urgently required.

**Comment by Serrarthu** [comment]
@gregsdennis Thanks for the swift diagnosis & solution. As I've mentioned in the SO question, I'm using a workaround involving the board ID for the moment, so there is no rush for the update on my side.

**Comment by gregsdennis** [comment]
Please see version 1.17.0 for the bug fix.
