### ISSUE TITLE
Cannot copy cards with short ID

### ISSUE THREAD

**Issue by agross** [gregsdennis/Manatee.Trello#83]
Hi,

I've just upgraded from Manatee.Trello 1.8.0 to 1.18 and I no longer can copy cards using the short card ID.

```cs
var cards = new Board("short board ID")
  .Lists["long list ID']
  .Cards

cards.Add(new Card("template card ID"));
```

The `"template card ID"` was OK to being a short ID with 1.8.0, but with 1.18 it needs to be a long ID.

The following is logged:

```
Sending: Post cards
Status Code: BadRequest (400), Content: Invalid objectId
```

**Comment by gregsdennis** [comment]
I don't think using the short ID was ever supported by the Trello API.  What may have been happening was that card details were downloaded upon Card instantiation, whereas in 1.18.x, this has been fixed to hold requests until the data is requested.  It looks like you were utilizing a side effect of a bug that has been fixed.

To fix the issue, you could try to access the card before passing it into the `Add(Card)` method.  Something like

    var source = new Card("template card ID");
    source.Refresh();
    cards.Add(source);

This will refresh the card data, including fetching the long ID.

**Comment by agross** [comment]
Yes, I just saw in the logs that Manatee.Trello received the card information before `PUT`ting the new card. I changed my code to only use long IDs. Let's keep the issue for documentation.
