### ISSUE TITLE
Can't retrieve list names

### ISSUE THREAD

**Issue by nhoway** [gregsdennis/Manatee.Trello#84]
Hi,

I am trying to retrieve lists' names from a board but the "Name" method does not returns anything in my code, is there a known issue about it ?

`listId = "12345678";`
`var myList = new List(listId);`
`Console.WriteLine(myList.Name); // nothing`
`Console.WriteLine(myList.Id); // 58e781265ed00f2b436f993f`

If I set the list' name before directly in my code, that works :
`listId = "12345678";`
`var myList = new List(listId);`
`myList.Name = "Overriding name in C#";`
`Console.WriteLine(myList.Name); // Overriding name in C#`
`Console.WriteLine(myList.Id); // 58e781265ed00f2b436f993f`

I also tried with board.Name and I am having the same issue. board.Url works,

Thank you for your help & your great work !

**Comment by gregsdennis** [comment]
Thanks for reporting this.  When you set the list name, do you see the change reflected *in Trello*?

**Comment by gregsdennis** [comment]
I've replicated the problem.  Continuing my investigation...

**Comment by gregsdennis** [comment]
Problem solved.  Please see Manatee.Trello v1.18.1 for the fix.

**Comment by nhoway** [comment]
Hi,

Thanks for your commit, the fix works great !

**Comment by gregsdennis** [comment]
No worries.  Let me know if you find any other issues.
