### ISSUE TITLE
System.TypeInitializationException on  var serializer = new ManateeSerializer();

### ISSUE THREAD

**Issue by kofarrell1076** [gregsdennis/Manatee.Trello#86]
I'm getting a System.TypeInitializationException error when I call  var serializer = new ManateeSerializer();

No other information back and stack trace doesn't tell me much. Any ideas?
thanks

**Comment by gregsdennis** [comment]
Can you give me some more details?  What version are you using (Nuget version and .Net version)?  The stack trace may not tell you much but it could tell me a lot. Are there inner exceptions?

I just released a new version last night (6.0.1) and all tests pass. The tests are run against the .Net 4.5 framework.  Is this what you're using?

**Comment by kofarrell1076** [comment]
Greg,
Thanks for the quick reply.  It’s latest version (installed today) 6.0.1 and running on .net 4.6. Maybe go back a version?

kevin

Sent from Mail for Windows 10

**Comment by gregsdennis** [comment]
I'll run a test from the Trello libs to see if I can reproduce this...

**Comment by kofarrell1076** [comment]
Greg,
Previous version 5.2.1 works. I’ll try and get you an inner exception dump from the latest. It may help.

kevin

Sent from Mail for Windows 10

**Comment by kofarrell1076** [comment]
Here you go.

Ex.Inner - System.IO.FileNotFoundException: Could not load file or assembly 'Manatee.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=c267f67a39449c62' or one of its dependencies. The system cannot find the file specified. File name: 'Manatee.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=c267f67a39449c62' at Manatee.Trello.ManateeJson.ManateeSerializer..cctor() WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Sent from Mail for Windows 10

**Comment by gregsdennis** [comment]
I'm unable to reproduce this, even with the updated packages.  Could you let me know what versions of the Manatee.Trello* libraries you're using, please?

**Comment by kofarrell1076** [comment]
.trello. 1.18.1
.trello.manateejson 1.8.1
.trello.webapi 1.1.0.1

**Comment by gregsdennis** [comment]
Okay.  I had to start a new project and target 4.6 to replicate but I got it.  Seems the 4.5 DLL didn't get packed into the Manatee.Json 6.0.1 package.  I'll have to publish an update to that.

As a workaround, you can manually reference the net40-client version from your local Nuget cache (packages/Manatee.Json.6.0.1 folder).  That *should* get you going.

>Also, please either adjust your email settings to not quote text or reply directly in GitHub.  I've had to edit all of your replies so far.  Thanks. 😄

**Comment by kofarrell1076** [comment]
Excellent. Great support btw.

thanks

**Comment by gregsdennis** [comment]
@kofarrell1076 I'll have an updated package for you soon (v6.0.1.1).  Please check it out and let me know.
