### ISSUE TITLE
Card Updating

### ISSUE THREAD

**Issue by brack4712** [gregsdennis/Manatee.Trello#89]
When you use Card.Updated, it doesn't seem to work..

I have this:
https://i.gyazo.com/fa20f6506f5599c8856bbbfe68d6e490.png

and whenever I add a comment or something, it doesn't do anything.

Am I doing something wrong or is this a bug?

**Comment by gregsdennis** [comment]
@brack4712 a couple questions:

1. Are you using webhooks?
2. If not, are you accessing the cards regularly?

I would suggest that you read the wiki pages, specifically the *Reading Data* portion of the *Getting Started* page to see how the cards update themselves and the *Webhooks* page.

**Comment by gregsdennis** [comment]
@brack4712 ping!
