### ISSUE TITLE
URL of Image file attachment is null

### ISSUE THREAD

**Issue by sorosliuncu** [gregsdennis/Manatee.Trello#91]
I tried to get the URL of the first attachment, which is an image file by using the following codes:

card.Attachments[0].Url

However, the Url is a null value. Is that supposed to be that? If so, how could I get the image URL of the attachment?

**Comment by gregsdennis** [comment]
That should be populated.  I'll look into it.

Thanks for the report.

**Comment by gregsdennis** [comment]
I've confirmed the issue.  I'll have a fix out this weekend sometime.

**Comment by gregsdennis** [comment]
Nope.  It's a typo in my code.  I'll have a fix out this weekend.

**Comment by gregsdennis** [comment]
@sorosliuncu please update Manatee.Trello to v1.18.3

**Comment by sorosliuncu** [comment]
@gregsdennis Thank you! I have update the package to v1.18.3 and it works perfectly!
