### ISSUE TITLE
Manatee.StateMachine still required?

### ISSUE THREAD

**Issue by ronwarner** [gregsdennis/Manatee.Trello#98]
I'm cleaning up NuGet packages in a solution using your library and have noticed that some of the projects have Manatee.StateMachine, which I suppose means that when I initially fetched Manatee.Trello from NuGet, the state machine was a dependency.  Is this not the case anymore?  Is it safe to remove this package?

**Comment by gregsdennis** [comment]
That's no longer a dependency. To be sure, try to uninstall. Nuget will prevent a dependency from being uninstalled.

**Comment by ronwarner** [comment]
Excellent.  I was able to uninstall without problems.
