### ISSUE TITLE
Compatibility between Manatee.Json and Manatee.Trello.CustomFields

### ISSUE THREAD

**Issue by ronwarner** [gregsdennis/Manatee.Trello#99]
I've noticed there is an update to Manatee.Json in the 7.x range.  I tried to update the package in NuGet, but could not because, according to the package manager, Manatee.Trello.CustomFields, which I'm also using, requires a version in the 6.x range.  Is this intentional/known/legitimate, or do I just have my NuGet packages all goofed up?

**Comment by gregsdennis** [comment]
I haven't been able to update the Trello library to netstandard yet. You can still use the 6.x version of Manatee.Json for now.

**Comment by gregsdennis** [comment]
Please see #43. It's pending a release from the MS .Net team (linked in the issue).

**Comment by ronwarner** [comment]
Ah okay, that explains it.  Thanks.
